### ISSUE TITLE
handle_fatal_signal (sig=6) in std::vector<std::string, std::allocator<std::string> >::_M_range_check  | c++/4.8.2/bits/stl_vector.h:794

### ISSUE THREAD

**Issue by rameshvs02** [facebook/mysql-5.6#174]
Server is crashing when we start the daemon with zero `--rocksdb-keep-log-file-num`

Testcase

Startup option `--default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB --rocksdb-keep-log-file-num=0`

GDB info

```
#0  0x00007f6a70e23741 in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000e4f6ba in my_write_core (sig=6) at /sda/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000ac7484 in handle_fatal_signal (sig=6) at /sda/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f6a6eba45f7 in raise () from /lib64/libc.so.6
#5  0x00007f6a6eba5ce8 in abort () from /lib64/libc.so.6
#6  0x00007f6a6f4a89d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#7  0x00007f6a6f4a6946 in ?? () from /lib64/libstdc++.so.6
#8  0x00007f6a6f4a6973 in std::terminate() () from /lib64/libstdc++.so.6
#9  0x00007f6a6f4a6b93 in __cxa_throw () from /lib64/libstdc++.so.6
#10 0x00007f6a6f4fba17 in std::__throw_out_of_range(char const*) () from /lib64/libstdc++.so.6
#11 0x0000000000f7cb97 in std::vector<std::string, std::allocator<std::string> >::_M_range_check (this=0x7fff252a8580, __n=2) at /usr/include/c++/4.8.2/bits/stl_vector.h:794
#12 0x0000000000f741a5 in std::vector<std::string, std::allocator<std::string> >::at (this=0x7fff252a8580, __n=2) at /usr/include/c++/4.8.2/bits/stl_vector.h:812
#13 0x0000000000f46765 in rocksdb::DBImpl::PurgeObsoleteFiles (this=0x7f6a6c930a00, state=...) at /sda/FB-mysql-5.6/rocksdb/db/db_impl.cc:831
#14 0x0000000000f46d44 in rocksdb::DBImpl::DeleteObsoleteFiles (this=0x7f6a6c930a00) at /sda/FB-mysql-5.6/rocksdb/db/db_impl.cc:865
#15 0x0000000000f5e7c2 in rocksdb::DB::Open (db_options=..., dbname="./.rocksdb", column_families=std::vector of length 2, capacity 2 = {...}, handles=0x7fff252a96e0, dbptr=0x7fff252a91a8) at /sda/FB-mysql-5.6/rocksdb/db/db_impl.cc:5387
#16 0x000000000108528d in rocksdb::TransactionDB::Open (db_options=..., txn_db_options=..., dbname="./.rocksdb", column_families=std::vector of length 2, capacity 2 = {...}, handles=0x7fff252a96e0, dbptr=0x1f96cc0 <rdb>) at /sda/FB-mysql-5.6/rocksdb/utilities/transactions/transaction_db_impl.cc:99
#17 0x0000000000ecabc2 in rocksdb_init_func (p=0x7f6a6c8f0100) at /sda/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:2603
#18 0x00000000009c9ebb in ha_initialize_handlerton (plugin=0x7f6a6cb29c50) at /sda/FB-mysql-5.6/sql/handler.cc:671
#19 0x0000000000b8c274 in plugin_initialize (plugin=0x7f6a6cb29c50) at /sda/FB-mysql-5.6/sql/sql_plugin.cc:1139
#20 0x0000000000b8cc23 in plugin_init (argc=0x1f57908 <remaining_argc>, argv=0x7f6a6c8202c0, flags=0) at /sda/FB-mysql-5.6/sql/sql_plugin.cc:1441
#21 0x00000000009b1259 in init_server_components () at /sda/FB-mysql-5.6/sql/mysqld.cc:5532
#22 0x00000000009b240a in mysqld_main (argc=16, argv=0x7f6a6c8202c0) at /sda/FB-mysql-5.6/sql/mysqld.cc:6329
#23 0x00000000009a85a0 in main (argc=16, argv=0x7fff252aa328) at /sda/FB-mysql-5.6/sql/main.cc:25
```

**Comment by barisfb** [comment]
Fixed, closing

**Comment by RoelVdP** [comment]
Ref #218
