### ISSUE TITLE
Assertion `BaseValid()' failed in void rocksdb::BaseDeltaIterator::Advance() | rocksdb/utilities/write_batch_with_index/write_batch_with_index.cc:202

### ISSUE THREAD

**Issue by rameshvs02** [facebook/mysql-5.6#185]
Testcase 

Startup option `--skip-innodb --rocksdb --default-storage-engine=rocksdb --default-tmp-storage-engine=MyISAM` 

```
DROP DATABASE test;CREATE DATABASE test;USE test;
CREATE TABLE t2(id INT NOT NULL PRIMARY KEY, data INT) Engine=MEMORY; 
INSERT INTO t2 VALUES (100,NULL),(150,"long varchar"),(200,"varchar"),(250,"long long long varchar"); 
create TABLE t1 (a int not null, b int not null, primary key(a,b)); 
INSERT INTO t1  VALUES (1,1); 
SELECT a FROM t1, t2 WHERE a=b AND (b NOT IN (SELECT a FROM t1 WHERE a > 4));
```

GDB info

```
#0  0x00007f167bc2b741 in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000e50092 in my_write_core (sig=6) at /sda/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000ac7e34 in handle_fatal_signal (sig=6) at /sda/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f16799ac5f7 in raise () from /lib64/libc.so.6
#5  0x00007f16799adce8 in abort () from /lib64/libc.so.6
#6  0x00007f16799a5566 in __assert_fail_base () from /lib64/libc.so.6
#7  0x00007f16799a5612 in __assert_fail () from /lib64/libc.so.6
#8  0x000000000115f06e in rocksdb::BaseDeltaIterator::Advance (this=0x7f16720132c0) at /sda/FB-mysql-5.6/rocksdb/utilities/write_batch_with_index/write_batch
_with_index.cc:202
#9  0x000000000115eb57 in rocksdb::BaseDeltaIterator::Next (this=0x7f16720132c0) at /sda/FB-mysql-5.6/rocksdb/utilities/write_batch_with_index/write_batch_wi
th_index.cc:101
#10 0x0000000000ed547c in ha_rocksdb::rnd_next_with_direction (this=0x7f16720a5210, buf=0x7f167204c410 "", move_forward=true) at /sda/FB-mysql-5.6/storage/ro
cksdb/ha_rocksdb.cc:6130
#11 0x0000000000ed2ec0 in ha_rocksdb::index_next_with_direction (this=0x7f16720a5210, buf=0x7f167204c410 "", move_forward=true) at /sda/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:5219
#12 0x0000000000ed2db2 in ha_rocksdb::index_next (this=0x7f16720a5210, buf=0x7f167204c410 "") at /sda/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:5189
#13 0x00000000009d288c in handler::index_next_same (this=0x7f16720a5210, buf=0x7f167204c410 "", key=0x7f167208e8d8 "\001", keylen=4) at /sda/FB-mysql-5.6/sql/handler.cc:4906
#14 0x00000000009cf452 in handler::ha_index_next_same (this=0x7f16720a5210, buf=0x7f167204c410 "", key=0x7f167208e8d8 "\001", keylen=4) at /sda/FB-mysql-5.6/sql/handler.cc:3123
#15 0x0000000000ceda3b in subselect_indexsubquery_engine::exec (this=0x7f167208ede0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:3161
#16 0x0000000000ce6263 in Item_subselect::exec (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item_subselect.cc:642
#17 0x0000000000ce673d in Item_in_subselect::exec (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item_subselect.cc:767
#18 0x0000000000ce62a5 in Item_subselect::exec (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item_subselect.cc:647
#19 0x0000000000ce673d in Item_in_subselect::exec (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item_subselect.cc:767
#20 0x0000000000ce8463 in Item_in_subselect::val_bool (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item_subselect.cc:1400
#21 0x00000000009dad0b in Item::val_bool_result (this=0x7f1672069880) at /sda/FB-mysql-5.6/sql/item.h:1255
#22 0x0000000000a13f79 in Item_in_optimizer::val_int (this=0x7f167206a7a0) at /sda/FB-mysql-5.6/sql/item_cmpfunc.cc:2340
#23 0x00000000009e16b0 in Item::val_bool (this=0x7f167206a7a0) at /sda/FB-mysql-5.6/sql/item.cc:284
#24 0x0000000000a0e259 in Item_func_not::val_int (this=0x7f16720699e8) at /sda/FB-mysql-5.6/sql/item_cmpfunc.cc:302
#25 0x00000000009e16b0 in Item::val_bool (this=0x7f16720699e8) at /sda/FB-mysql-5.6/sql/item.cc:284
#26 0x0000000000a1ed78 in Item_cond_and::val_int (this=0x7f1672099a10) at /sda/FB-mysql-5.6/sql/item_cmpfunc.cc:5444
#27 0x0000000000b48394 in evaluate_join_record (join=0x7f1672069d18, join_tab=0x7f1672099120) at /sda/FB-mysql-5.6/sql/sql_executor.cc:1499
#28 0x0000000000b47dc8 in sub_select (join=0x7f1672069d18, join_tab=0x7f1672099120, end_of_records=false) at /sda/FB-mysql-5.6/sql/sql_executor.cc:1314
#29 0x0000000000b475ab in do_select (join=0x7f1672069d18) at /sda/FB-mysql-5.6/sql/sql_executor.cc:950
#30 0x0000000000b455b1 in JOIN::exec (this=0x7f1672069d18) at /sda/FB-mysql-5.6/sql/sql_executor.cc:207
#31 0x0000000000ba9e11 in mysql_execute_select (thd=0x7f167758b000, select_lex=0x7f167758e9d0, free_join=true) at /sda/FB-mysql-5.6/sql/sql_select.cc:1133
#32 0x0000000000baa0eb in mysql_select (thd=0x7f167758b000, tables=0x7f16720412c8, wild_num=0, fields=..., conds=0x7f1672069ad8, order=0x7f167758eb98, group=0x7f167758ead0, having=0x0, select_options=2147748608, result=0x7f1672069cf0, unit=0x7f167758e378, select_lex=0x7f167758e9d0) at /sda/FB-mysql-5.6/sql/sql_select.cc:1254
#33 0x0000000000ba81d5 in handle_select (thd=0x7f167758b000, result=0x7f1672069cf0, setup_tables_done_option=0) at /sda/FB-mysql-5.6/sql/sql_select.cc:126
#34 0x0000000000b7daaa in execute_sqlcom_select (thd=0x7f167758b000, all_tables=0x7f16720412c8, last_timer=0x7f167c2259a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:5853
#35 0x0000000000b764de in mysql_execute_command (thd=0x7f167758b000, statement_start_time=0x7f167c224938, post_parse=0x7f167c2259a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:3239
#36 0x0000000000b8106c in mysql_parse (thd=0x7f167758b000, rawbuf=0x7f1672041010 "SELECT a FROM t1, t2 WHERE a=b AND (b NOT IN (SELECT a FROM t1 WHERE a > 4))", length=76, parser_state=0x7f167c2252f0, last_timer=0x7f167c2259a0, async_commit=0x7f167c22599f "") at /sda/FB-mysql-5.6/sql/sql_parse.cc:7379
#37 0x0000000000b726eb in dispatch_command (command=COM_QUERY, thd=0x7f167758b000, packet=0x7f1677742001 "", packet_length=76) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1595
#38 0x0000000000b70faf in do_command (thd=0x7f167758b000) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1071
#39 0x0000000000b36d70 in do_handle_one_connection (thd_arg=0x7f167758b000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:1071
#40 0x0000000000b3666f in handle_one_connection (arg=0x7f167758b000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:929
#41 0x00007f167bc26dc5 in start_thread () from /lib64/libpthread.so.0
#42 0x00007f1679a6d21d in clone () from /lib64/libc.so.6
```

**Comment by yoshinorim** [comment]
Thanks for the bug report. Verified as described.

**Comment by mariadb-DanielLee** [comment]
Cool, let me know when it is fixed and I will test it again.

Thanks

Regards,
—
Daniel Lee, QA Engineer
MariaDB, www.mariadb.com

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D54867
