### ISSUE TITLE
segfault during test-wisconsin 

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#186]
This is repeatable.

Command line from run $mysql_root/sql-bench

```
./test-wisconsin --server=mysql --user=root --password=pw --host=127.0.0.1  --log --create-options="engine=rocksdb DEFAULT COLLATE=latin1_bin" --loop-count=200
```

Using my.cnf

```
rocksdb_max_open_files=-1
rocksdb_max_background_compactions=16
rocksdb_max_total_wal_size=4G
rocksdb_max_background_flushes=4
rocksdb_block_size=8192
rocksdb_block_cache_size=40G
rocksdb_table_cache_numshardbits=6
rocksdb_write_sync=0

# rate limiter
rocksdb_bytes_per_sync=4194304
rocksdb_wal_bytes_per_sync=4194304
# rocksdb_rate_limiter_bytes_per_sec=41943040 #40MB/s if running 4x. If running 1x, you can set ~200MB or even more.

# triggering compaction if there are many sequential deletes
rocksdb_compaction_sequential_deletes=1800
rocksdb_compaction_sequential_deletes_window=2000

rocksdb_default_cf_options=write_buffer_size=128m;target_file_size_base=32m;max_bytes_for_level_base=512m;level0_file_num_compaction_trigger=4;level0_slowdown_writes_trigger=10;level0_stop_writes_trigger=15;max_write_buffer_number=4;compression_per_level=kNoCompression:kNoCompression:kNoCompression:kZlibCompression:kZlibCompression:kZlibCompression:kZlibCompression;compression_opts=-14:1:0;block_based_table_factory={cache_index_and_filter_blocks=1;filter_policy=bloomfilter:10:false;whole_key_filtering=1};level_compaction_dynamic_level_bytes=true

default-storage-engine=rocksdb
skip-innodb
default-tmp-storage-engine=MyISAM
rocksdb

long_query_time=10
long_query_time=1
skip_log_bin
sync_binlog=0

rocksdb_allow_concurrent_memtable_write=1
rocksdb_enable_write_thread_adaptive_yield=1
```

Fault is:

```
mysqld: /home/mcallaghan/mysql3/5.6/rocksdb/db/compaction_picker.cc:878: rocksdb::LevelCompactionPicker::PickFilesMarkedForCompactionExperimental(const string&, rocksdb::VersionStorageInfo*, rocksdb::CompactionInputFiles*, int*, int*)::<lambda(std::pair<int, rocksdb::FileMetaData*>)>: Assertion `!level_file.second->being_compacted' failed.
21:13:37 UTC - mysqld got signal 6 ;
```

Thread that gets fault:

```
#0  0x00007f6e2fceed02 in raise () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
#1  0x00007f6e2fcf0af6 in abort () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
#2  0x00007f6e2fce76c5 in __assert_fail_base () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
#3  0x00007f6e2fce7773 in  () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
#4  0x0000000000e350af in rocksdb::LevelCompactionPicker::PickFilesMarkedForCompactionExperimental(std::string const&, rocksdb::VersionStorageInfo*, rocksdb::CompactionInputFiles*, int*, int*) (__closure=<synthetic pointer>, level_file=...) at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_picker.cc:878
#5  0x0000000000e350af in rocksdb::LevelCompactionPicker::PickFilesMarkedForCompactionExperimental(std::string const&, rocksdb::VersionStorageInfo*, rocksdb::CompactionInputFiles*, int*, int*) (this=this@entry=0x7f6e2ec27de0, cf_name=..., vstorage=vstorage@entry=0x7f6e283b0030, inputs=inputs@entry=0x7f6e201fc810, level=level@entry=0x7f6e201fc778, output_level=output_level@entry=0x7f6e201fc77c) at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_picker.cc:896
#6  0x0000000000e3a675 in rocksdb::LevelCompactionPicker::PickCompaction(std::string const&, rocksdb::MutableCFOptions const&, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*) (this=0x7f6e2ec27de0, cf_name=..., mutable_cf_options=..., vstorage=0x7f6e283b0030, log_buffer=<optimized out>)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_picker.cc:964
#7  0x0000000000e1ab7c in rocksdb::ColumnFamilyData::PickCompaction(rocksdb::MutableCFOptions const&, rocksdb::LogBuffer*) (this=this@entry=0x7f6e2ed18e00, mutable_options=..., log_buffer=log_buffer@entry=0x7f6e201fd2e0) at /home/mcallaghan/mysql4/5.6/rocksdb/db/column_family.cc:700
#8  0x0000000000cfd5a0 in rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, void*) (this=this@entry=0x7f6e2ebcf400, made_progress=made_progress@entry=0x7f6e201fd0ee, job_context=job_context@entry=0x7f6e201fd120, log_buffer=log_buffer@entry=0x7f6e201fd2e0, arg=arg@entry=0x0)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:2875
#9  0x0000000000d131f5 in rocksdb::DBImpl::BackgroundCallCompaction(void*) (this=this@entry=0x7f6e2ebcf400, arg=arg@entry=0x0)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:2712
#10 0x0000000000d137db in rocksdb::DBImpl::BGWorkCompaction(void*) (arg=<optimized out>) at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:2566
#11 0x0000000000dc8b72 in rocksdb::ThreadPool::BGThread(unsigned long) (this=this@entry=0x7f6e2ec291c0, thread_id=thread_id@entry=15)
    at /home/mcallaghan/mysql4/5.6/rocksdb/util/thread_posix.cc:119
#12 0x0000000000dc8cd3 in rocksdb::BGThreadWrapper(void*) (arg=0x7f6e2ec341e0) at /home/mcallaghan/mysql4/5.6/rocksdb/util/thread_posix.cc:143
#13 0x00007f6e31a417f1 in start_thread () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
#14 0x00007f6e2fdc646d in clone () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
```

Other threads

```
#0  0x00007f6e31a49ebc in __lll_lock_wait () from /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
(gdb) where
#0  0x00007f6e31a49ebc in __lll_lock_wait () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
#1  0x00007f6e31a43f2c in pthread_mutex_lock () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
#2  0x0000000000d818a1 in rocksdb::port::Mutex::Lock() (this=this@entry=0x7f6e2ebcf638) at /home/mcallaghan/mysql4/5.6/rocksdb/port/port_posix.cc:59
#3  0x0000000000dd0ee2 in rocksdb::InstrumentedMutex::Lock() (this=0x7f6e2ebcf638) at /home/mcallaghan/mysql4/5.6/rocksdb/util/instrumented_mutex.cc:37
#4  0x0000000000dd0ee2 in rocksdb::InstrumentedMutex::Lock() (this=this@entry=0x7f6e2ebcf638) at /home/mcallaghan/mysql4/5.6/rocksdb/util/instrumented_mutex.cc:29
#5  0x0000000000e1af45 in rocksdb::ColumnFamilyData::GetThreadLocalSuperVersion(rocksdb::InstrumentedMutex*) (this=this@entry=0x7f6e2ed19500, db_mutex=db_mutex@entry=0x7f6e2ebcf638) at /home/mcallaghan/mysql4/5.6/rocksdb/db/column_family.cc:769
#6  0x0000000000cecf81 in rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*, bool*) (cfd=0x7f6e2ed19500, this=0x7f6e2ebcf400) at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:4827
#7  0x0000000000cecf81 in rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*, bool*) (this=0x7f6e2ebcf400, read_options=..., column_family=<optimized out>, key=..., value=0x7f6e209fd310, value_found=0x0) at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:3306
#8  0x0000000000ced883 in rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*) (this=<optimized out>, read_options=..., column_family=<optimized out>, key=..., value=<optimized out>) at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:3234
#9  0x0000000000ddf316 in rocksdb::StackableDB::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*) (this=<optimized out>, options=..., column_family=<optimized out>, key=..., value=<optimized out>) at /home/mcallaghan/mysql4/5.6/rocksdb/include/rocksdb/utilities/stackable_db.h:54
#10 0x0000000000cc97a9 in Dict_manager::is_drop_index_ongoing(_gl_index_id_s) (value=0x7f6e209fd310, key=..., this=0x17f24c0 <dict_manager>)
    at /home/mcallaghan/mysql4/5.6/storage/rocksdb/rdb_datadic.cc:2655
#11 0x0000000000cc97a9 in Dict_manager::is_drop_index_ongoing(_gl_index_id_s) (this=this@entry=0x17f24c0 <dict_manager>, gl_index_id=..., gl_index_id@entry=...)
    at /home/mcallaghan/mysql4/5.6/storage/rocksdb/rdb_datadic.cc:2866
#12 0x0000000000ca97f0 in Rdb_CompactionFilter::Filter(int, rocksdb::Slice const&, rocksdb::Slice const&, std::string*, bool*) const (this=0x7f6e1f01a000, level=<optimized out>, key=..., existing_value=..., new_value=<optimized out>, value_changed=<optimized out>) at /home/mcallaghan/mysql4/5.6/storage/rocksdb/ha_rocksdb.cc:1198
#13 0x0000000000e25bce in rocksdb::CompactionIterator::NextFromInput() (this=this@entry=0x7f6e1f036400)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_iterator.cc:170
#14 0x0000000000e260d1 in rocksdb::CompactionIterator::SeekToFirst() (this=this@entry=0x7f6e1f036400) at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_iterator.cc:61
#15 0x0000000000e2bcb4 in rocksdb::CompactionJob::ProcessKeyValueCompaction(rocksdb::CompactionJob::SubcompactionState*) (this=this@entry=0x7f6e209fdb60, sub_compact=0x7f6e1f022000) at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_job.cc:656
#16 0x0000000000e2d7dc in rocksdb::CompactionJob::Run() (this=this@entry=0x7f6e209fdb60) at /home/mcallaghan/mysql4/5.6/rocksdb/db/compaction_job.cc:481
#17 0x0000000000cfd10a in rocksdb::DBImpl::BackgroundCompaction(bool*, rocksdb::JobContext*, rocksdb::LogBuffer*, void*) (this=this@entry=0x7f6e2ebcf400, made_progress=made_progress@entry=0x7f6e209fe0ee, job_context=job_context@entry=0x7f6e209fe120, log_buffer=log_buffer@entry=0x7f6e209fe2e0, arg=arg@entry=0x7f6e1dffd930)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:3011
#18 0x0000000000d131f5 in rocksdb::DBImpl::BackgroundCallCompaction(void*) (this=this@entry=0x7f6e2ebcf400, arg=arg@entry=0x7f6e1dffd930)
    at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:2712
#19 0x0000000000d137db in rocksdb::DBImpl::BGWorkCompaction(void*) (arg=<optimized out>) at /home/mcallaghan/mysql4/5.6/rocksdb/db/db_impl.cc:2566
#20 0x0000000000dc8b72 in rocksdb::ThreadPool::BGThread(unsigned long) (this=this@entry=0x7f6e2ec291c0, thread_id=thread_id@entry=14)
    at /home/mcallaghan/mysql4/5.6/rocksdb/util/thread_posix.cc:119
#21 0x0000000000dc8cd3 in rocksdb::BGThreadWrapper(void*) (arg=0x7f6e2ec341d0) at /home/mcallaghan/mysql4/5.6/rocksdb/util/thread_posix.cc:143
#22 0x00007f6e31a417f1 in start_thread () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
#23 0x00007f6e2fdc646d in clone () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6

```

**Comment by siying** [comment]
In the test, do you do anything that might trigger manual compaction? Something like analyze table, alter table, drop index, etc?

**Comment by mdcallag** [comment]
Sometimes I run DROP DATABASE at test end and that triggers the crash. Full
SQL is in
https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/sql-bench/test-wisconsin.sh

On Mon, Feb 29, 2016 at 2:54 PM, Siying Dong notifications@github.com
wrote:

> In the test, do you do anything that might trigger manual compaction?
> Something like analyze table, alter table, drop index, etc?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/186#issuecomment-190436947.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by siying** [comment]
@mdcallag it might be a regression test introduced by the feature that manual compaction runs concurrently with automatic compactions. If it is easily reproducible. We can put a quick fix and see whether the problem can be fixed.

**Comment by mdcallag** [comment]
it is easy to reproduce

On Mon, Feb 29, 2016 at 3:05 PM, Siying Dong notifications@github.com
wrote:

> @mdcallag https://github.com/mdcallag it might be a regression test
> introduced by the feature that manual compaction runs concurrently with
> automatic compactions. If it is easily reproducible. We can put a quick fix
> and see whether the problem can be fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/186#issuecomment-190439781.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by siying** [comment]
Hope https://reviews.facebook.net/D54891 can fix it.

**Comment by yoshinorim** [comment]
I haven't been able to reproduce the crash, even without the Siying's diff. @mdcallag: Does the Siying's diff fix the crash on your machine?

**Comment by mdcallag** [comment]
MyRocks is at this diff for RocksDB:

commit 79ca039eb44546ddb71c1f6ba6626dc614a662a7

Author: Yueh-Hsuan Chiang yhchiang@fb.com

Date:   Fri Feb 19 14:42:24 2016 -0800

```
Relax the check condition of prefix_extractor in
```

CheckOptionsCompatibility

When I try arc patch I get:

```
This diff is against commit 5ea9aa3c146f77e45563f30f346aa3e8f66082c3,
```

but

```
the commit is nowhere in the working copy. Try to apply it against the

current working copy state? (79ca039eb44546ddb71c1f6ba6626dc614a662a7)
```

On Mon, Feb 29, 2016 at 5:19 PM, Yoshinori Matsunobu <
notifications@github.com> wrote:

> I haven't been able to reproduce the crash, even without the Siying's
> diff. @mdcallag https://github.com/mdcallag: Does the Siying's diff fix
> the crash on your machine?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/186#issuecomment-190479004.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by siying** [comment]
@mdcallag this is the diff https://github.com/facebook/rocksdb/commit/5ea9aa3c146f77e45563f30f346aa3e8f66082c3 . Did you pull?

**Comment by mdcallag** [comment]
Nope, just use what "git submodule update" gives me. Applied the patch and
so far no crash.

On Mon, Feb 29, 2016 at 6:23 PM, Siying Dong notifications@github.com
wrote:

> @mdcallag https://github.com/mdcallag this is the diff facebook/rocksdb@
> 5ea9aa3
> https://github.com/facebook/rocksdb/commit/5ea9aa3c146f77e45563f30f346aa3e8f66082c3
> . Did you pull?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/facebook/mysql-5.6/issues/186#issuecomment-190498628.

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D55233
