### ISSUE TITLE
InnoDB: Failing assertion: event in file os0sync.cc line 490

### ISSUE THREAD

**Issue by rameshvs02** [facebook/mysql-5.6#190]
Startup option
`--innodb-read-only=1`

Testcase
`SET GLOBAL innodb_status_output=OFF;`

GDB info

```
#0  0x00007f4abf3c7741 in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000e4f6ba in my_write_core (sig=6) at /sda/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000ac7484 in handle_fatal_signal (sig=6) at /sda/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f4abd1475f7 in raise () from /lib64/libc.so.6
#5  0x00007f4abd148ce8 in abort () from /lib64/libc.so.6
#6  0x00000000011ee8a4 in os_event_set2 (event=0x0) at /sda/FB-mysql-5.6/storage/innobase/os/os0sync.cc:490
#7  0x000000000117c756 in innodb_status_output_update (thd=0x7f4abad88000, var=0x1c84fa0 <mysql_sysvar_status_output>, var_ptr=0x1fbcb50 <srv_print_innodb_monitor>, save=0x7f4aa7041260) at /sda/FB-mysql-5.6/storage/innobase/handler/ha_innodb.cc:17421
#8  0x0000000000b913b7 in sys_var_pluginvar::global_update (this=0x7f4abaf39a48, thd=0x7f4abad88000, var=0x7f4aa7041240) at /sda/FB-mysql-5.6/sql/sql_plugin.cc:3277
#9  0x0000000000ac5075 in sys_var::update (this=0x7f4abaf39a48, thd=0x7f4abad88000, var=0x7f4aa7041240) at /sda/FB-mysql-5.6/sql/set_var.cc:193
#10 0x0000000000ac6158 in set_var::update (this=0x7f4aa7041240, thd=0x7f4abad88000) at /sda/FB-mysql-5.6/sql/set_var.cc:670
#11 0x0000000000ac5d29 in sql_set_variables (thd=0x7f4abad88000, var_list=0x7f4abad8bf70) at /sda/FB-mysql-5.6/sql/set_var.cc:573
#12 0x0000000000b7894c in mysql_execute_command (thd=0x7f4abad88000, statement_start_time=0x7f4abf96c938, post_parse=0x7f4abf96d9a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:4329
#13 0x0000000000b806bc in mysql_parse (thd=0x7f4abad88000, rawbuf=0x7f4aa7041010 "SET GLOBAL innodb_status_output=OFF", length=35, parser_state=0x7f4abf96d2f0, last_timer=0x7f4abf96d9a0, async_commit=0x7f4abf96d99f "") at /sda/FB-mysql-5.6/sql/sql_parse.cc:7379
#14 0x0000000000b71d3b in dispatch_command (command=COM_QUERY, thd=0x7f4abad88000, packet=0x7f4aaf64e001 "SET GLOBAL innodb_status_output=OFF", packet_length=35) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1595
#15 0x0000000000b705ff in do_command (thd=0x7f4abad88000) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1071
#16 0x0000000000b363c0 in do_handle_one_connection (thd_arg=0x7f4abad88000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:1071
#17 0x0000000000b35cbf in handle_one_connection (arg=0x7f4abad88000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:929
#18 0x00007f4abf3c2dc5 in start_thread () from /lib64/libpthread.so.0
#19 0x00007f4abd20821d in clone () from /lib64/libc.so.6
```

**Comment by jkedgar** [comment]
Pull Request: https://github.com/facebook/mysql-5.6/pull/558

**Comment by jkedgar** [comment]
This should now be fixed.
