### ISSUE TITLE
segfault with create/drop index concurrent with queries

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#192]
This occurred twice after a few minutes from my test case.

The add/drop index command uses the old-style table copy code.

The stack is:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb709700 (LWP 3413505)]
ha_rocksdb::info (this=0x7fffc9828710, flag=26) at /home/mcallaghan/mysql4/5.6/storage/rocksdb/ha_rocksdb.cc:6407
6407    /home/mcallaghan/mysql4/5.6/storage/rocksdb/ha_rocksdb.cc: No such file or directory.
(gdb) where
#0  0x0000000000c3da80 in ha_rocksdb::info(unsigned int) (this=0x7fffc9828710, flag=26) at /home/mcallaghan/mysql4/5.6/storage/rocksdb/ha_rocksdb.cc:6407
#1  0x0000000000c3c7e1 in ha_rocksdb::open(char const*, int, unsigned int) (this=0x7fffc9828710, name=<optimized out>, mode=<optimized out>, test_if_locked=<optimized out>) at /home/mcallaghan/mysql4/5.6/storage/rocksdb/ha_rocksdb.cc:3650
#2  0x000000000067d0f3 in handler::ha_open(TABLE*, char const*, int, int) (this=0x7fffc9828710, table_arg=table_arg@entry=0x7fffc9815000, name=0x7fffc3b01760 "./mysqlslap/a2", mode=mode@entry=2, test_if_locked=2) at /home/mcallaghan/mysql4/5.6/sql/handler.cc:2664
#3  0x000000000086a08b in open_table_from_share(THD*, TABLE_SHARE*, char const*, unsigned int, unsigned int, unsigned int, TABLE*, bool) (thd=thd@entry=
    0x7fffd4c772c0, share=share@entry=0x7fffc3b01410, alias=<optimized out>, db_stat=db_stat@entry=39, prgflag=prgflag@entry=44, ha_open_flags=<optimized out>, outparam=<optimized out>, is_create_table=<optimized out>) at /home/mcallaghan/mysql4/5.6/sql/table.cc:2660
#4  0x000000000078566d in open_table(THD*, TABLE_LIST*, Open_table_context*) (thd=thd@entry=0x7fffd4c772c0, table_list=table_list@entry=0x7fffc9823260, ot_ctx=ot_ctx@entry=0x7fffeb7061b0) at /home/mcallaghan/mysql4/5.6/sql/sql_base.cc:3184
#5  0x000000000078e326 in open_tables(THD*, TABLE_LIST**, unsigned int*, unsigned int, Prelocking_strategy*) (ot_ctx=0x7fffeb7061b0, has_prelocking_list=false, prelocking_strategy=0x7fffeb7063f0, flags=0, counter=0x7fffd4c7a4d0, tables=0x7fffc9823260, lex=0x7fffd4c7a420, thd=0x7fffd4c772c0)
    at /home/mcallaghan/mysql4/5.6/sql/sql_base.cc:4746
#6  0x000000000078e326 in open_tables(THD*, TABLE_LIST**, unsigned int*, unsigned int, Prelocking_strategy*) (thd=thd@entry=0x7fffd4c772c0, start=start@entry=0x7fffeb7063e8, counter=0x7fffd4c7a4d0, flags=flags@entry=0, prelocking_strategy=prelocking_strategy@entry=0x7fffeb7063f0)
    at /home/mcallaghan/mysql4/5.6/sql/sql_base.cc:5180
#7  0x000000000078ed40 in open_normal_and_derived_tables(THD*, TABLE_LIST*, unsigned int) (thd=thd@entry=0x7fffd4c772c0, tables=tables@entry=0x7fffc9823260, flags=flags@entry=0) at /home/mcallaghan/mysql4/5.6/sql/sql_base.cc:5893
#8  0x00000000005ffe80 in execute_sqlcom_select(THD*, TABLE_LIST*, ulonglong*) (thd=thd@entry=0x7fffd4c772c0, all_tables=0x7fffc9823260, last_timer=last_timer@entry=0x7fffeb7078e8) at /home/mcallaghan/mysql4/5.6/sql/sql_parse.cc:5885
#9  0x00000000007de227 in mysql_execute_command(THD*, unsigned long long*, unsigned long long*) (thd=thd@entry=0x7fffd4c772c0, statement_start_time=statement_start_time@entry=0x7fffeb7077d8, post_parse=post_parse@entry=0x7fffeb7078e8) at /home/mcallaghan/mysql4/5.6/sql/sql_parse.cc:3239
#10 0x00000000007e4c7b in mysql_parse(THD*, char*, unsigned int, Parser_state*, unsigned long long*, char*) (thd=thd@entry=0x7fffd4c772c0, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=0x7fffeb708060, last_timer=last_timer@entry=0x7fffeb7078e8, async_commit=async_commit@entry=0x7fffeb7078e7 "") at /home/mcallaghan/mysql4/5.6/sql/sql_parse.cc:7443
#11 0x00000000007e66d0 in dispatch_command(enum_server_command, THD*, char*, unsigned int) (command=COM_QUERY, thd=0x7fffd4c772c0, packet=<optimized out>, packet_length=<optimized out>) at /home/mcallaghan/mysql4/5.6/sql/sql_parse.cc:1595
#12 0x00000000007e7e45 in do_command(THD*) (thd=<optimized out>) at /home/mcallaghan/mysql4/5.6/sql/sql_parse.cc:1071
#13 0x00000000007a66fe in do_handle_one_connection(THD*) (thd_arg=<optimized out>) at /home/mcallaghan/mysql4/5.6/sql/sql_connect.cc:1071
#14 0x00000000007a6859 in handle_one_connection(void*) (arg=<optimized out>) at /home/mcallaghan/mysql4/5.6/sql/sql_connect.cc:929
#15 0x00007ffff776c7f1 in start_thread () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libpthread.so.0
#16 0x00007ffff5af146d in clone () at /usr/local/fbcode/gcc-4.9-glibc-2.20/lib/libc.so.6
```

The code is:

```
6393   if (flag & HA_STATUS_CONST)
6394   {
6395     ref_length= pk_descr->max_storage_fmt_length();
6396 
6397     // TODO: Needs to reimplement after having real index statistics
6398     for (uint i= 0; i < tbl_def->n_keys; i++)
6399     {
6400       if (is_hidden_pk(i, table, tbl_def))
6401       {
6402         continue;
6403       }
6404       KEY* k= &table->key_info[i];
6405       for (uint j = 0; j < k->actual_key_parts; j++)
6406       {
6407         uint x = key_descr[i]->stats.distinct_keys_per_prefix.size() > j && key_descr[i]->stats.distinct_keys_per_prefix[j] > 0 ?
6408           key_descr[i]->stats.rows / key_descr[i]->stats.distinct_keys_per_prefix[j] :
6409           0;
6410         if (x > stats.records)
6411           x = stats.records;
6412         if ((x == 0 && rocksdb_debug_optimizer_no_zero_cardinality) ||
6413             rocksdb_debug_optimizer_n_rows > 0)
```

Test case is:

```
iter=$1
dop=$2

bin/mysql -uroot -ppw -e "drop database mysqlslap; create database mysqlslap"
bin/mysql -uroot -ppw mysqlslap -e "CREATE TABLE a2 (a int, b int);INSERT INTO a2 VALUES (1,1)"

bin/mysqlslap -uroot -ppw --delimiter=";" --query="alter table a2 add index bx(b); alter table a2 drop index bx" --concurrency=1 --iterations=$iter >& o.j1 &
id1=$!
sleep 1

bin/mysqlslap -uroot -ppw --delimiter=";" --query="alter table a2 add index ax(a); alter table a2 drop index ax" --concurrency=1 --iterations=$iter >& o.j2 &
id2=$!
sleep 1

bin/mysqlslap -uroot -ppw --delimiter=";" --query="select * from a2 where a=1" --concurrency=$dop --iterations=$iter >& o.j3 &
id3=$!

bin/mysqlslap -uroot -ppw --delimiter=";" --query="select * from a2 where b=1" --concurrency=$dop --iterations=$iter >& o.j4

echo Wait for $id1
wait $id1
echo Wait for $id2
wait $id2
echo Wait for $id3
wait $id3
```

Command line was:  for i in $( seq 1 1000 ); do bash rslap.sh 1000 64 ; done

RocksDB specific my.cnf:

```
rocksdb_max_open_files=-1
rocksdb_max_background_compactions=16
rocksdb_max_total_wal_size=4G
rocksdb_max_background_flushes=4
rocksdb_block_size=8192
rocksdb_block_cache_size=40G
rocksdb_table_cache_numshardbits=6

rocksdb_block_cache_size=16M
rocksdb_table_cache_numshardbits=1

rocksdb_write_sync=0

# rate limiter
rocksdb_bytes_per_sync=4194304
rocksdb_wal_bytes_per_sync=4194304
# rocksdb_rate_limiter_bytes_per_sec=41943040 #40MB/s if running 4x. If running 1x, you can set ~200MB or even more.

# triggering compaction if there are many sequential deletes
rocksdb_compaction_sequential_deletes=1800
rocksdb_compaction_sequential_deletes_window=2000

rocksdb_default_cf_options=write_buffer_size=4m;target_file_size_base=32m;max_bytes_for_level_base=128m;level0_file_num_compaction_trigger=8;level0_slowdown_writes_trigger=20;level0_stop_writes_trigger=30;max_write_buffer_number=2;compression_per_level=kNoCompression:kNoCompression:kNoCompression:kZlibCompression:kZlibCompression:kZlibCompression:kZlibCompression;compression_opts=-14:1:0;block_based_table_factory={cache_index_and_filter_blocks=1;filter_policy=bloomfilter:10:false;whole_key_filtering=1};level_compaction_dynamic_level_bytes=true

default-storage-engine=rocksdb
skip-innodb
default-tmp-storage-engine=MyISAM
rocksdb

long_query_time=10
long_query_time=1
skip_log_bin
sync_binlog=0

rocksdb_allow_concurrent_memtable_write=1
rocksdb_enable_write_thread_adaptive_yield=1
```

**Comment by hermanlee** [comment]
I am having some problems reproducing the crash with my mysqld builds (in either debug or release build). Since it happens two minutes into the test, is the rslap.sh script running with parameters iter=1000 and dop=1 and waiting for the two concurrent mysqlslap alter table processes to complete? Do you still have the your build for me to try and trigger the crash on?

Side note: we need to be adding more of these types of mysqlslap tests in the myrocks test suite.

**Comment by mdcallag** [comment]
Reproduced again as described but took 1 hour. gdb was attached. Previously it reproduced faster with and without gdb attached.

**Comment by yoshinorim** [comment]
Herman's diff https://reviews.facebook.net/D55071 fixed the issue. Please reopen if you still find the same problem.
