### ISSUE TITLE
SELECT ... FOR UPDATE SKIP LOCKED causes assert failure

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#196]
The following will cause crash. The issue is not specific to MyRocks, I can observe with engine=heap as well.

```
create table t1 (a int primary key) engine=rocksdb;
insert into t1 values (1),(2);
select * from t1 for update ignore locked;
```

```
  Program received signal SIGABRT, Aborted.
  [Switching to Thread 0x7ffff7f4d700 (LWP 9578)]
  0x00007ffff5d6ef79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
  56    ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)  

(gdb) wher
  #0  0x00007ffff5d6ef79 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
  #1  0x00007ffff5d72388 in __GI_abort () at abort.c:89
  #2  0x00007ffff5d67e36 in __assert_fail_base (fmt=0x7ffff5eb9718 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x16946d0 "table->reginfo.x_lock_type == TL_X_LOCK_REGULAR", file=file@entry=0x16942c8 "/home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/lock.cc", line=line@entry=752, function=function@entry=0x1694a80 <get_lock_data(THD*, TABLE**, unsigned int, unsigned int)::__PRETTY_FUNCTION__> "MYSQL_LOCK* get_lock_data(THD*, TABLE**, uint, uint)") at assert.c:92
  #3  0x00007ffff5d67ee2 in __GI___assert_fail (assertion=0x16946d0 "table->reginfo.x_lock_type == TL_X_LOCK_REGULAR", file=0x16942c8 "/home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/lock.cc", line=752, function=0x1694a80 <get_lock_data(THD*, TABLE**, unsigned int, unsigned int)::__PRETTY_FUNCTION__> "MYSQL_LOCK* get_lock_data(THD*, TABLE**, uint, uint)") at assert.c:101
  #4  0x0000000000d24bee in get_lock_data (thd=0x235e0b0, table_ptr=0x7fffac0062d8, count=1, flags=2) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/lock.cc:752
  #5  0x0000000000d237fb in mysql_lock_tables (thd=0x235e0b0, tables=0x7fffac0062d8, count=1, flags=0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/lock.cc:305
  #6  0x0000000000b2d76d in lock_tables (thd=0x235e0b0, tables=0x7fffac005640, count=1, flags=0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_base.cc:6092
  #7  0x0000000000bd0d2c in mysql_select (thd=0x235e0b0, tables=0x7fffac005640, wild_num=1, fields=..., conds=0x0, order=0x2361c58, group=0x2361b90, having=0x0, select_options=2147748608, result=0x7fffac005c80, unit=0x2361438, select_lex=0x2361a90) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_select.cc:1234
  #8  0x0000000000bcecaa in handle_select (thd=0x235e0b0, result=0x7fffac005c80, setup_tables_done_option=0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_select.cc:126
  #9  0x0000000000ba25bc in execute_sqlcom_select (thd=0x235e0b0, all_tables=0x7fffac005640, last_timer=0x7ffff7f4b7d0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_parse.cc:5917
  #10 0x0000000000b9a9fa in mysql_execute_command (thd=0x235e0b0, statement_start_time=0x7ffff7f4b658, post_parse=0x7ffff7f4b7d0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_parse.cc:3239
  #11 0x0000000000ba5c93 in mysql_parse (thd=0x235e0b0, rawbuf=0x7fffac0053e0 "select * from t1 for update skip locked", length=39, parser_state=0x7ffff7f4c010, last_timer=0x7ffff7f4b7d0, async_commit=0x7ffff7f4b7a8 "") at /home/psergey/dev-git/mysql-5.6-rocksdb-look40/sql/sql_parse.cc:7449
```

The reason is that the assert

```
      DBUG_ASSERT(table->reginfo.x_lock_type == TL_X_LOCK_REGULAR);
```

and if statement above assume that any storage engine will have

```
table->file->support_x_lock_type()== true
```

which is not the case. Should MyRocks support this improved locking?

**Comment by pengtfb** [comment]
I am looking into it. BTW, the syntax should be ... SKIP LOCKED, not Ignore Locked, right?

**Comment by pengtfb** [comment]
Fixed by https://github.com/facebook/mysql-5.6/commit/cfe2d83bfd5471767a3a00cbf7d450d33fa0d9fe
