### ISSUE TITLE
handle_fatal_signal (sig=11) in key_unpack | FB-mysql-5.6/sql/key.cc:457

### ISSUE THREAD

**Issue by rameshvs02** [facebook/mysql-5.6#213]
Testcase

```
DROP DATABASE test;CREATE DATABASE test;USE test;
CREATE TABLE t1(a INT,b INT,KEY (b)) engine=rocksdb PARTITION BY HASH(a) PARTITIONS 2;
INSERT INTO t1(a)VALUES (20010101101010.999949);
lock tables t1 write,t1 as t0 write,t1 as t2 write;
SELECT a FROM t1 ORDER BY a;
truncate t1;
INSERT INTO t1 VALUES(X'042000200020',X'042000200020'),(X'200400200020',X'200400200020');
```

GDB info

```
#0  0x00007efcdc58e741 in pthread_kill () from /lib64/libpthread.so.0
#1  0x0000000000e8e89a in my_write_core (sig=11) at /sda/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000b04359 in handle_fatal_signal (sig=11) at /sda/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x0000000000ae3687 in key_unpack (to=0x7efcdcb32c50, table=0x7efcd30be000, key=0x7efcd305cdd8) at /sda/FB-mysql-5.6/sql/key.cc:457
#5  0x0000000000a0bef9 in print_keydup_error (table=0x7efcd30be000, key=0x7efcd305cdd8, msg=0x7efcd8191ed3 "Duplicate entry '%-.64s' for key '%-.192s'", errflag=0) at /sda/FB-mysql-5.6/sql/handler.cc:3794
#6  0x0000000000a0c01a in print_keydup_error (table=0x7efcd30be000, key=0x7efcd305cdd8, errflag=0) at /sda/FB-mysql-5.6/sql/handler.cc:3815
#7  0x0000000000a0c29c in handler::print_error (this=0x7efcd309bb10, error=121, errflag=0) at /sda/FB-mysql-5.6/sql/handler.cc:3882
#8  0x00000000014af08a in ha_partition::print_error (this=0x7efcd30ac010, error=121, errflag=0) at /sda/FB-mysql-5.6/sql/ha_partition.cc:8119
#9  0x0000000000b94ef4 in write_record (thd=0x7efcd819c000, table=0x7efcd30be000, info=0x7efcdcb35560, update=0x7efcdcb355e0) at /sda/FB-mysql-5.6/sql/sql_insert.cc:1908
#10 0x0000000000b92c14 in mysql_insert (thd=0x7efcd819c000, table_list=0x7efcd3041178, fields=..., values_list=..., update_fields=..., update_values=..., duplic=DUP_ERROR, ignore=false) at /sda/FB-mysql-5.6/sql/sql_insert.cc:1030
#11 0x0000000000bb4f10 in mysql_execute_command (thd=0x7efcd819c000, statement_start_time=0x7efcdcb36828, post_parse=0x7efcdcb378a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:4123
#12 0x0000000000bbdcfd in mysql_parse (thd=0x7efcd819c000, rawbuf=0x7efcd3041010 "INSERT INTO t1 VALUES(X'042000200020',X'042000200020'),(X'200400200020',X'200400200020')", length=88, parser_state=0x7efcdcb371e0, last_timer=0x7efcdcb378a0, async_commit=0x7efcdcb3789f "") at /sda/FB-mysql-5.6/sql/sql_parse.cc:7539
#13 0x0000000000baed7b in dispatch_command (command=COM_QUERY, thd=0x7efcd819c000, packet=0x7efcd558c001 "INSERT INTO t1 VALUES(X'042000200020',X'042000200020'),(X'200400200020',X'200400200020')", packet_length=88) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1595
#14 0x0000000000bad63f in do_command (thd=0x7efcd819c000) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1071
#15 0x0000000000b733be in do_handle_one_connection (thd_arg=0x7efcd819c000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:1095
#16 0x0000000000b72bdf in handle_one_connection (arg=0x7efcd819c000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:929
#17 0x00007efcdc589dc5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007efcda3cf21d in clone () from /lib64/libc.so.6
(gdb) +set logging off
```

**Comment by yoshinorim** [comment]
Thanks! Verified as described. It didn't reproduce with InnoDB. MyRocks has little test coverage for partitions so more bugs can be expected.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D55887
