### ISSUE TITLE
handle_fatal_signal (sig=11) in Field_long::cmp | FB-mysql-5.6/sql/field.cc:4067

### ISSUE THREAD

**Issue by rameshvs02** [facebook/mysql-5.6#214]
Testcase

```
# mysqld options required for replay:  --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB
DROP DATABASE test;CREATE DATABASE test;USE test;
create TABLE t1(a int,b int,c int,primary key(a,b)) partition by list (b*a) (partition x1 values in (1) tablespace ts1,partition x2 values in (3,11,5,7) tablespace ts2,partition x3 values in (16,8,5+19,70-43) tablespace ts3);
create table t2(b binary(2) ) engine=rocksdb;
xa start 'test-bad';
set session optimizer_switch=5;
insert into t1(a,b)values(1,7);
select a from t1 where a in(select a from t1 where a in (select b from t2));
```

GDB info

```
#0  0x00007f7cac015741 in __pthread_kill (threadid=<optimized out>, signo=11) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:61
#1  0x0000000000e8e89a in my_write_core (sig=11) at /sda/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000b04359 in handle_fatal_signal (sig=11) at /sda/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x0000000000ce6c74 in Field_long::cmp (this=0x7f7ca284b070, a_ptr=0x100000002 <Address 0x100000002 out of bounds>, b_ptr=0x301000f <Address 0x301000f out
 of bounds>) at /sda/FB-mysql-5.6/sql/field.cc:4067
#5  0x0000000000d01244 in Field::cmp_max (this=0x7f7ca284b070, a=0x100000002 <Address 0x100000002 out of bounds>, b=0x301000f <Address 0x301000f out of bounds>, max_len=4) at /sda/FB-mysql-5.6/sql/field.h:1000
#6  0x0000000000ae3d05 in key_rec_cmp (key_p=0x7f7ca28b59f0, first_rec=0x100000001 <Address 0x100000001 out of bounds>, second_rec=0x301000e <Address 0x301000e out of bounds>) at /sda/FB-mysql-5.6/sql/key.cc:740
#7  0x0000000000e8e39b in _downheap (queue=0x7f7ca28b5a20, idx=1) at /sda/FB-mysql-5.6/mysys/queues.c:287
#8  0x0000000000e8e301 in queue_remove (queue=0x100000002, idx=1) at /sda/FB-mysql-5.6/mysys/queues.c:257
#9  0x00000000014abedb in ha_partition::handle_ordered_next (this=0x7f7ca28b5610, buf=0x7f7ca284b030 "\002\001", is_next_same=true) at /sda/FB-mysql-5.6/sql/ha_partition.cc:6438
#10 0x00000000014aa61b in ha_partition::index_next_same (this=0x7f7ca28b5610, buf=0x7f7ca284b030 "\002\001", key=0x7f7ca286af68 "\001", keylen=4) at /sda/FB-mysql-5.6/sql/ha_partition.cc:5746
#11 0x0000000000a0b05c in handler::ha_index_next_same (this=0x7f7ca28b5610, buf=0x7f7ca284b030 "\002\001", key=0x7f7ca286af68 "\001", keylen=4) at /sda/FB-mysql-5.6/sql/handler.cc:3183
#12 0x0000000000d2b8a3 in subselect_indexsubquery_engine::exec (this=0x7f7ca28993f0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:3161
#13 0x0000000000d240cb in Item_subselect::exec (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:642
#14 0x0000000000d245a5 in Item_in_subselect::exec (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:767
#15 0x0000000000d2410d in Item_subselect::exec (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:647
#16 0x0000000000d245a5 in Item_in_subselect::exec (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:767
#17 0x0000000000d262cb in Item_in_subselect::val_bool (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item_subselect.cc:1400
#18 0x0000000000a16b33 in Item::val_bool_result (this=0x7f7ca2896de0) at /sda/FB-mysql-5.6/sql/item.h:1255
#19 0x0000000000a4fdfd in Item_in_optimizer::val_int (this=0x7f7ca2869560) at /sda/FB-mysql-5.6/sql/item_cmpfunc.cc:2340
#20 0x0000000000b849fc in evaluate_join_record (join=0x7f7ca2897090, join_tab=0x7f7ca286a458) at /sda/FB-mysql-5.6/sql/sql_executor.cc:1499
#21 0x0000000000b84430 in sub_select (join=0x7f7ca2897090, join_tab=0x7f7ca286a458, end_of_records=false) at /sda/FB-mysql-5.6/sql/sql_executor.cc:1314
#22 0x0000000000b83c13 in do_select (join=0x7f7ca2897090) at /sda/FB-mysql-5.6/sql/sql_executor.cc:950
#23 0x0000000000b81c19 in JOIN::exec (this=0x7f7ca2897090) at /sda/FB-mysql-5.6/sql/sql_executor.cc:207
#24 0x0000000000be786d in mysql_execute_select (thd=0x7f7ca799c000, select_lex=0x7f7ca799f9e0, free_join=true) at /sda/FB-mysql-5.6/sql/sql_select.cc:1133
#25 0x0000000000be7b47 in mysql_select (thd=0x7f7ca799c000, tables=0x7f7ca28412c0, wild_num=0, fields=..., conds=0x7f7ca2896de0, order=0x7f7ca799fba8, group=0x7f7ca799fae0, having=0x0, select_options=2148797184, result=0x7f7ca2897068, unit=0x7f7ca799f388, select_lex=0x7f7ca799f9e0) at /sda/FB-mysql-5.6/sql/sql_select.cc:1254
#26 0x0000000000be5c31 in handle_select (thd=0x7f7ca799c000, result=0x7f7ca2897068, setup_tables_done_option=0) at /sda/FB-mysql-5.6/sql/sql_select.cc:126
#27 0x0000000000bba565 in execute_sqlcom_select (thd=0x7f7ca799c000, all_tables=0x7f7ca28412c0, last_timer=0x7f7cac5be8a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:5917
#28 0x0000000000bb2b6c in mysql_execute_command (thd=0x7f7ca799c000, statement_start_time=0x7f7cac5bd828, post_parse=0x7f7cac5be8a0) at /sda/FB-mysql-5.6/sql/sql_parse.cc:3239
#29 0x0000000000bbdcfd in mysql_parse (thd=0x7f7ca799c000, rawbuf=0x7f7ca2841010 "select a from t1 where a in(select a from t1 where a in (select b from t2))", length=75, parser_state=0x7f7cac5be1e0, last_timer=0x7f7cac5be8a0, async_commit=0x7f7cac5be89f "") at /sda/FB-mysql-5.6/sql/sql_parse.cc:7539
#30 0x0000000000baed7b in dispatch_command (command=COM_QUERY, thd=0x7f7ca799c000, packet=0x7f7ca4d8c001 "", packet_length=75) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1595
#31 0x0000000000bad63f in do_command (thd=0x7f7ca799c000) at /sda/FB-mysql-5.6/sql/sql_parse.cc:1071
#32 0x0000000000b733be in do_handle_one_connection (thd_arg=0x7f7ca799c000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:1095
#33 0x0000000000b72bdf in handle_one_connection (arg=0x7f7ca799c000) at /sda/FB-mysql-5.6/sql/sql_connect.cc:929
#34 0x00007f7cac010dc5 in start_thread (arg=0x7f7cac5bf700) at pthread_create.c:308
#35 0x00007f7ca9e5628d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by yoshinorim** [comment]
Thanks! Verified as described. It didn't reproduce with InnoDB. MyRocks has little test coverage for partitions so more bugs can be expected.

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D56475
