### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' in rocksdb::DBImpl::PurgeObsoleteFiles when using --rocksdb-keep-log-file-num=0

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#218]
```
2016-03-23 18:44:59 3139 [Note]     target_file_size_base=2097152
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
07:44:59 UTC - mysqld got signal 6 ;
```

To trigger, start server with;

```
 --no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB --rocksdb-keep-log-file-num=0
```

Backtrace;

```
+bt
#0  0x00007f153d9a5741 in __pthread_kill (threadid=<optimized out>, signo=6) at ../nptl/sysdeps/unix/sysv/linux/pthread_kill.c:61
#1  0x0000000000e8eaaa in my_write_core (sig=6) at /git/FB-mysql-5.6/mysys/stacktrace.c:422
#2  0x0000000000b04475 in handle_fatal_signal (sig=6) at /git/FB-mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f153b9325f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#5  0x00007f153b933ce8 in __GI_abort () at abort.c:90
#6  0x00007f153c2369d5 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#7  0x00007f153c234946 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:38
#8  0x00007f153c234973 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#9  0x00007f153c234b93 in __cxxabiv1::__cxa_throw (obj=0x7f1539a6f940, tinfo=0x1fc9600 <_ZTISt12out_of_range@@GLIBCXX_3.4>, dest=0x9e2ad0 <_ZNSt12out_of_rangeD1Ev@plt>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#10 0x00007f153c289a17 in std::__throw_out_of_range (__s=<optimized out>) at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:80
#11 0x0000000000f5dc11 in std::vector<std::string, std::allocator<std::string> >::_M_range_check (this=0x7fff45d94100, __n=0) at /usr/include/c++/4.8.2/bits/stl_vector.h:794
#12 0x0000000000f54a07 in std::vector<std::string, std::allocator<std::string> >::at (this=0x7fff45d94100, __n=0) at /usr/include/c++/4.8.2/bits/stl_vector.h:812
#13 0x0000000000f25224 in rocksdb::DBImpl::PurgeObsoleteFiles (this=0x7f1539b82e00, state=...) at /git/FB-mysql-5.6/rocksdb/db/db_impl.cc:836
#14 0x0000000000f25804 in rocksdb::DBImpl::DeleteObsoleteFiles (this=0x7f1539b82e00) at /git/FB-mysql-5.6/rocksdb/db/db_impl.cc:870
#15 0x0000000000f3db42 in rocksdb::DB::Open (db_options=..., dbname="./.rocksdb", column_families=std::vector of length 1, capacity 1 = {...}, handles=0x7fff45d95280, dbptr=0x7fff45d94d48) at /git/FB-mysql-5.6/rocksdb/db/db_impl.cc:5467
#16 0x0000000001078289 in rocksdb::TransactionDB::Open (db_options=..., txn_db_options=..., dbname="./.rocksdb", column_families=std::vector of length 1, capacity 1 = {...}, handles=0x7fff45d95280, dbptr=0x200efc0 <myrocks::rdb>) at /git/FB-mysql-5.6/rocksdb/utilities/transactions/transaction_db_impl.cc:103
#17 0x0000000000ea4730 in myrocks::rocksdb_init_func (p=0x7f1539bda780) at /git/FB-mysql-5.6/storage/rocksdb/ha_rocksdb.cc:2759
#18 0x0000000000a0632f in ha_initialize_handlerton (plugin=0x7f1539b2ce90) at /git/FB-mysql-5.6/sql/handler.cc:671
#19 0x0000000000bca784 in plugin_initialize (plugin=0x7f1539b2ce90) at /git/FB-mysql-5.6/sql/sql_plugin.cc:1139
#20 0x0000000000bcb133 in plugin_init (argc=0x1fcf9a8 <remaining_argc>, argv=0x7f1539a52ac0, flags=0) at /git/FB-mysql-5.6/sql/sql_plugin.cc:1441
#21 0x00000000009ed417 in init_server_components () at /git/FB-mysql-5.6/sql/mysqld.cc:5550
#22 0x00000000009ee5df in mysqld_main (argc=15, argv=0x7f1539a52ac0) at /git/FB-mysql-5.6/sql/mysqld.cc:6348
#23 0x00000000009e46f0 in main (argc=15, argv=0x7fff45d95ee8) at /git/FB-mysql-5.6/sql/main.cc:25
```

**Comment by RoelVdP** [comment]
Issue #174 shows the same crash, but a fix for that bug was committed 12 days ago. My build is from 21.03.16.
