### ISSUE TITLE
linkbench can't connect via JDBC

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#233]
linkbench connections fail after https://github.com/facebook/mysql-5.6/commit/b98a293e02fc70db676882a8e6b06190774263ab. These use JDBC and MySQL Connector/J http://dev.mysql.com/doc/refman/5.6/en/connector-j-info.html

```
ERROR 2016-04-21 11:40:20,332 [Thread-1]: error connecting to database:
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.Util.getInstance(Util.java:387)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:917)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2332)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2085)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:795)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:400)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:327)
        at java.sql.DriverManager.getConnection(DriverManager.java:582)
        at java.sql.DriverManager.getConnection(DriverManager.java:185)
        at com.facebook.LinkBench.LinkStoreMysql.openConnection(LinkStoreMysql.java:153)
        at com.facebook.LinkBench.LinkStoreMysql.initialize(LinkStoreMysql.java:122)
        at com.facebook.LinkBench.NodeLoader.run(NodeLoader.java:114)
        at com.facebook.LinkBench.LinkBenchDriver$1.run(LinkBenchDriver.java:439)
        at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.NullPointerException
```

**Comment by ghost** [comment]
Jay and I were debugging this Wednesday night. I also traced it down to the b98a293 commit. One of the changes in that commit is the following diff in sql/sql_acl.cc 

```
-  end= strnmov(end, server_version, SERVER_VERSION_LENGTH) + 1;
+  end= strnmov(end, MYSQL_COMPILATION_COMMENT, SERVER_VERSION_LENGTH) + 1;
```

which changes the string stored to represent the server version.

The prior code used char\* server_version which is "5.6.27-log" 

The new code uses MYSQL_COMPILATION_COMMENT which is "Source distribution"

This breaks the JDBC connector (and subsequently Linkbench) because the JDBC connector requests the server_version from the MySQL server (in MysqlIO.cc:doHandshake()) and it expects the string to have a major.minor.micro version number in it like 5.6.27 but instead gets "Source Distribution". The JDBC code has many if statements that check to make sure the server version meets a minimum version number. These all fail, and eventually the JDBC code attempts to access an internal variable (ConnectorImpl.serverVariables) that never gets initialized because a code fragment doesn't get run.  

 If you back out this one line in sql/sql_acl.cc, MySQL compiles again and JDBC connects fine. 

The JDBC code for reference is at: https://github.com/mysql/mysql-connector-j.git

Should I submit a pull request for this one line change?

**Comment by mdcallag** [comment]
For the one line change to what - JDBC or our code?

**Comment by ghost** [comment]
I was referring to a one line change to your MySQL branch. However, it is probably no longer necessary. 

Jay mentioned this morning that Alex's intention was to simply include more info than just the existing major.minor.micro version in the name and that it worked with the terminal client, but not JDBC and that Alex will likely have a fix out soon.

**Comment by alxyang** [comment]
The reason we changed from server_version to MYSQL_COMPILATION_COMMENT during the handshake was to hopefully get the RPM version in the server handshake for an internal task.  

E.G. instead of 5.6.24 we would get something like 5.6.24-20160220.prod

Seems like in the case of the JDBC connector it will not work.  I will revert the commit for now.

**Comment by alxyang** [comment]
above commit should have fixed the issue.
