### ISSUE TITLE
MyRocks strange behavior with limit rows examined

### ISSUE THREAD

**Issue by tplavcic** [facebook/mysql-5.6#241]
MyRocks seems to ignore the limit rows examined but it doesn't throw an error on query execution.
So FB-InnoDB gives a warning about that the number of the rows examined will be higher than the limit and stops the query execution, but MyRocks just executed the query like there's no such limit present. If it's not supported it should throw an error.

FB-InnoDB:

```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.28 sec)

mysql> select avg(a) from t1 limit rows examined 1;
Empty set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                         |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1892 | Query execution was interrupted. The query examined at least 4 rows, which exceeds LIMIT ROWS EXAMINED (1). The query result may be incomplete. |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into t1 values (1),(2),(3),(4);
Query OK, 4 rows affected (0.04 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> select avg(a) from t1 limit rows examined 1;
Empty set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                         |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1892 | Query execution was interrupted. The query examined at least 4 rows, which exceeds LIMIT ROWS EXAMINED (1). The query result may be incomplete. |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from t1 limit rows examined 1;
Empty set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                                                         |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Warning | 1892 | Query execution was interrupted. The query examined at least 4 rows, which exceeds LIMIT ROWS EXAMINED (1). The query result may be incomplete. |
+---------+------+-------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

FB-MyRocks:

```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.12 sec)

mysql> select avg(a) from t1 limit rows examined 1;
+--------+
| avg(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.00 sec)

mysql> insert into t1 values (1),(2),(3),(4);
Query OK, 4 rows affected (0.00 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> select avg(a) from t1 limit rows examined 1;
+--------+
| avg(a) |
+--------+
| 2.5000 |
+--------+
1 row in set (0.00 sec)

mysql> select * from t1 limit rows examined 1;
+------+
| a    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.00 sec)
```

**Comment by yoshinorim** [comment]
MyRocks has not supported rows examined yet. This is a good feature request.

**Comment by tplavcic** [comment]
Agreed that it can be a feature request, but if it doesn't support it it should throw an error when you issue the query - oracle mysql does that.

```
mysql> select * from t1 limit rows examined 1;
(1327, u'Undeclared variable: rows')
```

**Comment by spetrunia** [comment]
Was wondering how it could happen that InnoDB (or HEAP) work while MyRocks doesn't.

The reason is as follows.  LIMIT ROWS EXAMINED is checked by THD::check_limit_rows_examined:

```
  Hardware watchpoint 4: *$a
  Old value = THD::NOT_KILLED
  New value = THD::ABORT_QUERY
  THD::check_limit_rows_examined (this=0x2306080) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/sql_class.cc:4758
```

The check is invoked from here:

```
(gdb) wher
  #0  THD::check_limit_rows_examined (this=0x2306080) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/sql_class.cc:4758
  #1  0x0000000000a39e7e in handler::ha_statistic_increment (this=0x7fffe4014ce0, offset=&system_status_var::ha_read_rnd_next_count) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/handler.cc:2598
  #2  0x000000000150be7b in ha_heap::rnd_next (this=0x7fffe4014ce0, buf=0x7fffe4015088 "\375\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/storage/heap/ha_heap.cc:396
  #3  0x0000000000a3ac6f in handler::ha_rnd_next (this=0x7fffe4014ce0, buf=0x7fffe4015088 "\375\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/handler.cc:2909
  #4  0x0000000000dc4cf7 in rr_sequential (info=0x7fffe4006c28) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/records.cc:480
  #5  0x0000000000bc959c in sub_select (join=0x7fffe4005d78, join_tab=0x7fffe4006b98, end_of_records=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/sql_executor.cc:1297
  #6  0x0000000000bc8e56 in do_select (join=0x7fffe4005d78) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/sql_executor.cc:950
  #7  0x0000000000bc6e09 in JOIN::exec (this=0x7fffe4005d78) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100/sql/sql_executor.cc:207
```

That is, the check is done in ha_statistic_increment call, like in the below
code:

```
int ha_heap::rnd_next(uchar *buf)
{
  MYSQL_READ_ROW_START(table_share->db.str, table_share->table_name.str,
                       TRUE);
  ha_statistic_increment(&SSV::ha_read_rnd_next_count);

```

MyRocks needs to add ha_statistic_increment calls.
