### ISSUE TITLE
rocksdb.add_index_inplace test reports 'corrupted unsorted chunks:'

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#295]
When I run rocksdb.add_index_inplace test, it produces warnings like this:

```
TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
*** Error in `/home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/mysqld': free(): corrupted unsorted chunks: 0x00007fbd340b1ba0 ***
rocksdb.add_index_inplace                [ pass ]  11866
--------------------------------------------------------------------------
```

I can reproduce with both debug and valgrind+debug builds on a recent tree.
When I tried to run this test with --valgrind, it hung (not sure why).

**Comment by spetrunia** [comment]
The test leaves behind a core file.

When I load it, I get this:

```
  Program terminated with signal SIGABRT, Aborted.
  #0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
  62    ../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.
(gdb) wher
  #0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
  #1  0x0000000001029544 in my_write_core (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/mysys/stacktrace.c:422
  #2  0x0000000000c4473b in handle_fatal_signal (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/signal_handler.cc:239
  #3  <signal handler called>
  #4  0x00007fbd49c78267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
  #5  0x00007fbd49c79eca in __GI_abort () at abort.c:89
  #6  0x00007fbd49cbbc53 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fbd49dd41a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
  #7  0x00007fbd49cc3c69 in malloc_printerr (ptr=<optimized out>, str=0x7fbd49dd4248 "free(): corrupted unsorted chunks", action=1) at malloc.c:4965
  #8  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
  #9  0x00007fbd49cc789c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
  #10 0x00000000010203c4 in my_free (ptr=0x7fbd340b1ba0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/mysys/my_malloc.c:140
  #11 0x000000000142237f in myrocks::Rdb_key_def::~Rdb_key_def (this=0x7fbd340b1a60, __in_chrg=<optimized out>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/storage/rocksdb/rdb_datadic.cc:118
  #12 0x00000000014216a0 in __gnu_cxx::new_allocator<myrocks::Rdb_key_def>::destroy<myrocks::Rdb_key_def> (this=0x7fbd340b1a60, __p=0x7fbd340b1a60) at /usr/include/c++/4.9/ext/new_allocator.h:124
  #13 0x00000000014213b9 in std::allocator_traits<std::allocator<myrocks::Rdb_key_def> >::_S_destroy<myrocks::Rdb_key_def> (__a=..., __p=0x7fbd340b1a60) at /usr/include/c++/4.9/bits/alloc_traits.h:282
  #14 0x000000000142104d in std::allocator_traits<std::allocator<myrocks::Rdb_key_def> >::destroy<myrocks::Rdb_key_def> (__a=..., __p=0x7fbd340b1a60) at /usr/include/c++/4.9/bits/alloc_traits.h:411
  #15 0x0000000001420453 in std::_Sp_counted_ptr_inplace<myrocks::Rdb_key_def, std::allocator<myrocks::Rdb_key_def>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x7fbd340b1a50) at /usr/include/c++/4.9/bits/shared_ptr_base.h:524
  #16 0x0000000000af7c6c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7fbd340b1a50) at /usr/include/c++/4.9/bits/shared_ptr_base.h:149
  #17 0x0000000000af601d in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fbd493bc5a8, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/shared_ptr_base.h:666
  #18 0x00000000013f3412 in std::__shared_ptr<myrocks::Rdb_key_def, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fbd493bc5a0, __in_chrg=<optimized out>) at /usr/include/c++/4.9/bits/shared_ptr_base.h:914
  #19 0x0000000001401a14 in std::__shared_ptr<myrocks::Rdb_key_def, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<myrocks::Rdb_key_def, (__gnu_cxx::_Lock_policy)2>&&) (this=0x7fbd340cd568, __r=<unknown type in /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/mysqld, CU 0x22736cc, DIE 0x2340446>) at /usr/include/c++/4.9/bits/shared_ptr_base.h:993
  #20 0x00000000013fb5f2 in std::shared_ptr<myrocks::Rdb_key_def>::operator=(std::shared_ptr<myrocks::Rdb_key_def>&&) (this=0x7fbd340cd568, __r=<unknown type in /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/mysqld, CU 0x22736cc, DIE 0x2335f78>) at /usr/include/c++/4.9/bits/shared_ptr.h:291
  #21 0x0000000001426c27 in myrocks::Rdb_tbl_def::~Rdb_tbl_def (this=0x7fbd340b15a0, __in_chrg=<optimized out>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/storage/rocksdb/rdb_datadic.cc:2111
  #22 0x00000000013eab4b in myrocks::ha_rocksdb::commit_inplace_alter_table (this=0x7fbd340d21a0, altered_table=0x7fbd3409bf60, ha_alter_info=0x7fbd493bca60, commit=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/storage/rocksdb/ha_rocksdb.cc:9449
  #23 0x0000000000b19eb6 in handler::ha_commit_inplace_alter_table (this=0x7fbd340d21a0, altered_table=0x7fbd3409bf60, ha_alter_info=0x7fbd493bca60, commit=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/handler.cc:4682
  #24 0x00000000017819b5 in ha_partition::commit_inplace_alter_table (this=0x7fbd340d0c80, altered_table=0x7fbd3409bf60, ha_alter_info=0x7fbd493bca60, commit=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/ha_partition.cc:8462
  #25 0x0000000000b19eb6 in handler::ha_commit_inplace_alter_table (this=0x7fbd340d0c80, altered_table=0x7fbd3409bf60, ha_alter_info=0x7fbd493bca60, commit=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/handler.cc:4682
  #26 0x0000000000d8253d in mysql_inplace_alter_table (thd=0x3ec10a0, table_list=0x7fbd34005520, table=0x7fbd340d1340, altered_table=0x7fbd3409bf60, ha_alter_info=0x7fbd493bca60, inplace_supported=HA_ALTER_INPLACE_SHARED_LOCK_AFTER_PREPARE, target_mdl_request=0x7fbd493bcad0, alter_ctx=0x7fbd493bd1f0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_table.cc:6835
  #27 0x0000000000d87806 in mysql_alter_table (thd=0x3ec10a0, new_db=0x7fbd34005a88 "test", new_name=0x0, create_info=0x7fbd493be180, table_list=0x7fbd34005520, alter_info=0x7fbd493be260, order_num=0, order=0x0, ignore=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_table.cc:8868
  #28 0x0000000000eecd5a in Sql_cmd_alter_table::execute (this=0x7fbd34005bd8, thd=0x3ec10a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_alter.cc:335
  #29 0x0000000000d08e16 in mysql_execute_command (thd=0x3ec10a0, statement_start_time=0x7fbd493bf9c0, post_parse=0x7fbd493bfaf8) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_parse.cc:5780
  #30 0x0000000000d0d5af in mysql_parse (thd=0x3ec10a0, rawbuf=0x7fbd34005400 "ALTER TABLE t1 ADD INDEX kij(i,j), ALGORITHM=INPLACE", length=52, parser_state=0x7fbd493c0380, last_timer=0x7fbd493bfaf8, async_commit=0x7fbd493bfacc "", db="test", exit_admission_control=0x7fbd493bfbb0 "") at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_parse.cc:7674
  #31 0x0000000000cfde86 in dispatch_command (command=COM_QUERY, thd=0x3ec10a0, packet=0x3ed3651 "ALTER TABLE t1 ADD INDEX kij(i,j), ALGORITHM=INPLACE", packet_length=52) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_parse.cc:1691
  #32 0x0000000000cfc386 in do_command (thd=0x3ec10a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_parse.cc:1133
  #33 0x0000000000cbe496 in do_handle_one_connection (thd_arg=0x3ec10a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_connect.cc:1108
  #34 0x0000000000cbdc3f in handle_one_connection (arg=0x3ec10a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look100-vg2/sql/sql_connect.cc:929
  #35 0x00007fbd4a8416aa in start_thread (arg=0x7fbd493c1700) at pthread_create.c:333
  #36 0x00007fbd49d49eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The tree's tip cset is c1e0325f99b2f42b4a053a10ae362bea35c6c5a8.

**Comment by spetrunia** [comment]
It seems to be in online ALTER TABLE, so cc'ing @alxyang
