### ISSUE TITLE
rocksdb.bulk_load test times out

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#428]
``rocksb.bulk_load`` fails with a timeout in the current MyRocks tree. It has been failing for me for a while.

I tried increasing the timeout to 30 minutes (passed --testcase-timeout=30 option to mysql-test-run, it didn't help.
Looking at CPU and IO usage, I see that the system is idle for the most of the duration of the test run.

The failure looks as follows:
```
==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
worker[1] Test still running: rocksdb.bulk_load
worker[1] Trying to dump core for [mysqltest - pid: 9140, winpid: 9140]
worker[1] Trying to dump core for [mysqld.1 - pid: 9099, winpid: 9099]
rocksdb.bulk_load                        [ fail ]  timeout after 1800 seconds
        Test ended at 2016-11-16 18:59:31

Test case timeout after 1800 seconds
```

```
== /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/log/bulk_load.log == 
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin';
CREATE TABLE t2(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin';
CREATE TABLE t3(pk CHAR(5) PRIMARY KEY, a char(30), b char(30), key(a)) COLLATE 'latin1_bin'
  PARTITION BY KEY() PARTITIONS 4;
set session transaction isolation level repeatable read;
select * from information_schema.rocksdb_dbstats where stat_type='DB_NUM_SNAPSHOTS';
STAT_TYPE       VALUE
DB_NUM_SNAPSHOTS        0
start transaction with consistent snapshot;
select * from information_schema.rocksdb_dbstats where stat_type='DB_NUM_SNAPSHOTS';
STAT_TYPE       VALUE
DB_NUM_SNAPSHOTS        1
set rocksdb_bulk_load=1;
set rocksdb_bulk_load_size=100000;
LOAD DATA INFILE <input_file> INTO TABLE t1;
LOAD DATA INFILE <input_file> INTO TABLE t2;
LOAD DATA INFILE <input_file> INTO TABLE t3;

```
```
 == /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/tmp/analyze-timeout-mysqld.1.err ==
mysqltest: Could not open connection 'default' after 500 attempts: 2002 Can't connect to local MySQL server through socket '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/tmp/mysqld.1.sock' (111)


 - saving '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/log/rocksdb.bulk_load/' to '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/log/rocksdb.bulk_load/'
 - found 'core' (0/5)

Trying 'dbx' to get a backtrace

Trying 'gdb' to get a backtrace
Core generated by '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld'
Output from gdb follows. The first stack trace is from the failing thread.
The following stack traces are from all threads (so the failing one is
duplicated).
--------------------------
[New LWP 9100]
[New LWP 9136]
[New LWP 9101]
[New LWP 9135]
[New LWP 9134]
[New LWP 9139]
[New LWP 9205]
[New LWP 9204]
[New LWP 9206]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld --defaults-group-suffi'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
62      ../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.
#0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x0000000001066cdf in my_write_core (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysys/stacktrace.c:422
#2  0x0000000000c9a719 in handle_fatal_signal (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f18678648dd in poll () at ../sysdeps/unix/syscall-template.S:81
#5  0x0000000000b43cc4 in handle_connections_sockets (admin=false, socket_ptr=0x0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:8131
#6  0x0000000000b41e49 in handle_connections_sockets_all () at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:6850
#7  0x0000000000b42bee in mysqld_main (argc=88, argv=0x40ef790) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:7489
#8  0x0000000000b353f6 in main (argc=14, argv=0x7ffefe206f38) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/main.cc:25

Thread 9 (Thread 0x7f185e7fc700 (LWP 9206)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000168c37d in rocksdb::(anonymous namespace)::ConditionWait (condition=..., lock=...) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:97
#2  0x000000000168c7fb in rocksdb::ThreadPoolImpl::BGThread (this=0x3fc7800, thread_id=0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:175
#3  0x000000000168ca8f in rocksdb::BGThreadWrapper (arg=0x7f1848000b10) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:253
#4  0x00007f18683676aa in start_thread (arg=0x7f185e7fc700) at pthread_create.c:333
#5  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 8 (Thread 0x7f1866e96700 (LWP 9204)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000106afd9 in safe_cond_wait (cond=0x23521a0 <COND_thread_cache>, mp=0x2350600 <LOCK_thread_count>, file=0x17d0808 "/home/psergey/dev-git/mysql-5.6-rocksdb-look2/include/mysql/psi/mysql_thread.h", line=1177) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysys/thr_mutex.c:240
#2  0x0000000000b356f9 in inline_mysql_cond_wait (that=0x23521a0 <COND_thread_cache>, mutex=0x2350600 <LOCK_thread_count>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/include/mysql/psi/mysql_thread.h:1177
#3  0x0000000000b3a66b in block_until_new_connection_halflock () at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:3153
#4  0x0000000000b3a985 in one_thread_per_connection_end (thd=0x428bd00, block_pthread=true) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:3251
#5  0x0000000000d14a56 in do_handle_one_connection (thd_arg=0x428bd00) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_connect.cc:1166
#6  0x0000000000d140f8 in handle_one_connection (arg=0x428bd00) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_connect.cc:960
#7  0x00007f18683676aa in start_thread (arg=0x7f1866e96700) at pthread_create.c:333
#8  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 7 (Thread 0x7f185dffb700 (LWP 9205)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000168c37d in rocksdb::(anonymous namespace)::ConditionWait (condition=..., lock=...) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:97
#2  0x000000000168c7fb in rocksdb::ThreadPoolImpl::BGThread (this=0x3fc78e8, thread_id=0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:175
#3  0x000000000168ca8f in rocksdb::BGThreadWrapper (arg=0x7f185008fc10) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/threadpool_imp.cc:253
#4  0x00007f18683676aa in start_thread (arg=0x7f185dffb700) at pthread_create.c:333
#5  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 6 (Thread 0x7f1866ee7700 (LWP 9139)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f1868107d1c in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00000000015a67db in std::condition_variable::wait<rocksdb::WriteThread::BlockingAwaitState(rocksdb::WriteThread::Writer*, uint8_t)::<lambda()> >(std::unique_lock<std::mutex> &, rocksdb::WriteThread::<lambda()>) (this=0x7f1866ee3990, __lock=..., __p=...) at /usr/include/c++/4.9/condition_variable:98
#3  0x00000000015a52c1 in rocksdb::WriteThread::BlockingAwaitState (this=0x3fc2be0, w=0x7f1866ee38f0, goal_mask=14 '\016') at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/write_thread.cc:37
#4  0x00000000015a567c in rocksdb::WriteThread::AwaitState (this=0x3fc2be0, w=0x7f1866ee38f0, goal_mask=14 '\016', ctx=0x23d3c10 <rocksdb::WriteThread::JoinBatchGroup(rocksdb::WriteThread::Writer*)::ctx>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/write_thread.cc:157
#5  0x00000000015a5c49 in rocksdb::WriteThread::JoinBatchGroup (this=0x3fc2be0, w=0x7f1866ee38f0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/write_thread.cc:227
#6  0x00000000014a0b05 in rocksdb::DBImpl::WriteImpl (this=0x3fc24e0, write_options=..., my_batch=0x7f1850090550, callback=0x0, log_used=0x0, log_ref=0, disable_memtable=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/db_impl.cc:4635
#7  0x00000000014a0832 in rocksdb::DBImpl::Write (this=0x3fc24e0, write_options=..., my_batch=0x7f1850090550) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/db_impl.cc:4585
#8  0x00000000016be16b in rocksdb::TransactionImpl::Commit (this=0x7f18500903b0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/utilities/transactions/transaction_impl.cc:250
#9  0x00000000013fc393 in myrocks::Rdb_transaction_impl::commit_no_binlog (this=0x7f18500902a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:1990
#10 0x00000000013fba6a in myrocks::Rdb_transaction::flush_batch (this=0x7f18500902a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:1783
#11 0x00000000013e7e02 in myrocks::ha_rocksdb::do_bulk_commit (this=0x7f18508a2740, tx=0x7f18500902a0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:7336
#12 0x00000000013e9ca1 in myrocks::ha_rocksdb::update_write_row (this=0x7f18508a2740, old_data=0x0, new_data=0x7f18500ae158 "\371qwcnvzcueSOtTQzUuwqATD9j", ' ' <repeats 11 times>, "VZH3hKzj2BTnN0VoIJ1pR         vtnVzsSTDbLoEpPZ0117j   RIhEifNl2qRSauo", ' ' <repeats 15 times>, "\b\t=p\001", skip_unique_check=true) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:8089
#13 0x00000000013e8264 in myrocks::ha_rocksdb::write_row (this=0x7f18508a2740, buf=0x7f18500ae158 "\371qwcnvzcueSOtTQzUuwqATD9j", ' ' <repeats 11 times>, "VZH3hKzj2BTnN0VoIJ1pR         vtnVzsSTDbLoEpPZ0117j   RIhEifNl2qRSauo", ' ' <repeats 15 times>, "\b\t=p\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:7437
#14 0x0000000000b7a064 in handler::ha_write_row (this=0x7f18508a2740, buf=0x7f18500ae158 "\371qwcnvzcueSOtTQzUuwqATD9j", ' ' <repeats 11 times>, "VZH3hKzj2BTnN0VoIJ1pR         vtnVzsSTDbLoEpPZ0117j   RIhEifNl2qRSauo", ' ' <repeats 15 times>, "\b\t=p\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/handler.cc:7708
#15 0x0000000001782507 in ha_partition::write_row (this=0x7f18500460f0, buf=0x7f18500ae158 "\371qwcnvzcueSOtTQzUuwqATD9j", ' ' <repeats 11 times>, "VZH3hKzj2BTnN0VoIJ1pR         vtnVzsSTDbLoEpPZ0117j   RIhEifNl2qRSauo", ' ' <repeats 15 times>, "\b\t=p\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/ha_partition.cc:4124
#16 0x0000000000b7a064 in handler::ha_write_row (this=0x7f18500460f0, buf=0x7f18500ae158 "\371qwcnvzcueSOtTQzUuwqATD9j", ' ' <repeats 11 times>, "VZH3hKzj2BTnN0VoIJ1pR         vtnVzsSTDbLoEpPZ0117j   RIhEifNl2qRSauo", ' ' <repeats 15 times>, "\b\t=p\001") at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/handler.cc:7708
#17 0x0000000000d37f1f in write_record (thd=0x4275500, table=0x7f18500457a0, info=0x7f1866ee4260, update=0x0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_insert.cc:1879
#18 0x0000000000f559e8 in read_sep_field (thd=0x4275500, info=..., table_list=0x7f18500578d0, fields_vars=..., set_fields=..., set_values=..., read_info=..., enclosed=..., skip_lines=0, ignore_check_option_errors=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_load.cc:1188
#19 0x0000000000f53975 in mysql_load (thd=0x4275500, ex=0x7f1850057848, table_list=0x7f18500578d0, fields_vars=..., set_fields=..., set_values=..., handle_duplicates=DUP_ERROR, ignore=false, read_file_from_client=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_load.cc:560
#20 0x0000000000d594cb in mysql_execute_command (thd=0x4275500, statement_start_time=0x7f1866ee5970, post_parse=0x7f1866ee5aa0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_parse.cc:4502
#21 0x0000000000d618ee in mysql_parse (thd=0x4275500, rawbuf=0x7f1850057670 "LOAD DATA INFILE '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/mysqld.1/data/test_loadfile.txt' INTO TABLE t3", length=125, parser_state=0x7f1866ee6330, last_timer=0x7f1866ee5aa0, async_commit=0x7f1866ee5a74 "", db="test", exit_admission_control=0x7f1866ee5b50 "") at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_parse.cc:7727
#22 0x0000000000d5202e in dispatch_command (command=COM_QUERY, thd=0x4275500, packet=0x4287a91 "LOAD DATA INFILE '/home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysql-test/var/mysqld.1/data/test_loadfile.txt' INTO TABLE t3", packet_length=125) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_parse.cc:1679
#23 0x0000000000d5060e in do_command (thd=0x4275500) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_parse.cc:1134
#24 0x0000000000d1494f in do_handle_one_connection (thd_arg=0x4275500) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_connect.cc:1139
#25 0x0000000000d140f8 in handle_one_connection (arg=0x4275500) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/sql_connect.cc:960
#26 0x00007f18683676aa in start_thread (arg=0x7f1866ee7700) at pthread_create.c:333
#27 0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 5 (Thread 0x7f185cff9700 (LWP 9134)):
#0  0x00007f1867833c4d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f1867866e84 in usleep (useconds=<optimized out>) at ../sysdeps/unix/sysv/linux/usleep.c:32
#2  0x00000000016166e1 in rocksdb::(anonymous namespace)::PosixEnv::SleepForMicroseconds (this=0x23d4600 <rocksdb::Env::Default()::default_env>, micros=405661603) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/util/env_posix.cc:628
#3  0x00000000014a2c6a in rocksdb::DBImpl::DelayWrite (this=0x3fc24e0, num_bytes=4300013) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/db_impl.cc:5051
#4  0x00000000014a164a in rocksdb::DBImpl::WriteImpl (this=0x3fc24e0, write_options=..., my_batch=0x7f183c000be0, callback=0x0, log_used=0x0, log_ref=0, disable_memtable=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/db_impl.cc:4778
#5  0x00000000014a0832 in rocksdb::DBImpl::Write (this=0x3fc24e0, write_options=..., my_batch=0x7f183c000be0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/rocksdb/db/db_impl.cc:4585
#6  0x0000000001434a26 in myrocks::Rdb_dict_manager::commit (this=0x23c0dc0 <myrocks::dict_manager>, batch=0x7f183c000be0, sync=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/rdb_datadic.cc:4004
#7  0x0000000001433393 in myrocks::Rdb_ddl_manager::persist_stats (this=0x23c0f80 <myrocks::ddl_manager>, sync=false) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/rdb_datadic.cc:3526
#8  0x00000000013f1ae7 in myrocks::Rdb_background_thread::run (this=0x23c9500 <myrocks::rdb_bg_thread>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:10544
#9  0x00000000014825d2 in myrocks::Rdb_thread::thread_func (thread_ptr=0x23c9500 <myrocks::rdb_bg_thread>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/rdb_threads.cc:33
#10 0x00007f18683676aa in start_thread (arg=0x7f185cff9700) at pthread_create.c:333
#11 0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 4 (Thread 0x7f185d7fa700 (LWP 9135)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
#1  0x000000000106b1a5 in safe_cond_timedwait (cond=0x23c9b48 <myrocks::rdb_drop_idx_thread+136>, mp=0x23c9ad8 <myrocks::rdb_drop_idx_thread+24>, abstime=0x7f185d7f9b70, file=0x1a8fa48 "/home/psergey/dev-git/mysql-5.6-rocksdb-look2/include/mysql/psi/mysql_thread.h", line=1214) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysys/thr_mutex.c:278
#2  0x00000000013d7ed2 in inline_mysql_cond_timedwait (that=0x23c9b48 <myrocks::rdb_drop_idx_thread+136>, mutex=0x23c9ad8 <myrocks::rdb_drop_idx_thread+24>, abstime=0x7f185d7f9b70) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/include/mysql/psi/mysql_thread.h:1214
#3  0x00000000013ec444 in myrocks::Rdb_drop_index_thread::run (this=0x23c9ac0 <myrocks::rdb_drop_idx_thread>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/ha_rocksdb.cc:9033
#4  0x00000000014825d2 in myrocks::Rdb_thread::thread_func (thread_ptr=0x23c9ac0 <myrocks::rdb_drop_idx_thread>) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/storage/rocksdb/rdb_threads.cc:33
#5  0x00007f18683676aa in start_thread (arg=0x7f185d7fa700) at pthread_create.c:333
#6  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7f1867768700 (LWP 9101)):
#0  0x00007f186779f993 in do_sigwaitinfo (info=0x7f1867767c70, set=<optimized out>) at ../sysdeps/unix/sysv/linux/sigwaitinfo.c:55
#1  __GI___sigwaitinfo (set=0x7f1867767bf0, info=0x7f1867767c70) at ../sysdeps/unix/sysv/linux/sigwaitinfo.c:80
#2  0x000000000106f161 in timer_notify_thread_func (arg=0x7ffefe206970) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysys/posix_timers.c:77
#3  0x00007f18683676aa in start_thread (arg=0x7f1867768700) at pthread_create.c:333
#4  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7f1866f38700 (LWP 9136)):
#0  do_sigwait (sig=0x7f1866f37c70, set=<optimized out>) at ../sysdeps/unix/sysv/linux/sigwait.c:64
#1  __sigwait (set=<optimized out>, sig=0x7f1866f37c70) at ../sysdeps/unix/sysv/linux/sigwait.c:96
#2  0x0000000000b3c7d1 in signal_hand (arg=0x0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:4178
#3  0x00007f18683676aa in start_thread (arg=0x7f1866f38700) at pthread_create.c:333
#4  0x00007f186786feed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f1869a25940 (LWP 9100)):
#0  __pthread_kill (threadid=<optimized out>, signo=6) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x0000000001066cdf in my_write_core (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/mysys/stacktrace.c:422
#2  0x0000000000c9a719 in handle_fatal_signal (sig=6) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x00007f18678648dd in poll () at ../sysdeps/unix/syscall-template.S:81
#5  0x0000000000b43cc4 in handle_connections_sockets (admin=false, socket_ptr=0x0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:8131
#6  0x0000000000b41e49 in handle_connections_sockets_all () at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:6850
#7  0x0000000000b42bee in mysqld_main (argc=88, argv=0x40ef790) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/mysqld.cc:7489
#8  0x0000000000b353f6 in main (argc=14, argv=0x7ffefe206f38) at /home/psergey/dev-git/mysql-5.6-rocksdb-look2/sql/main.cc:25

--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 1862 seconds executing testcases

Completed: Failed 1/1 tests, 0.00% were successful.

Failing test(s): rocksdb.bulk_load

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

mysql-test-run: *** ERROR: there were failing test cases
```

**Comment by jkedgar** [comment]
This is known to fail on the debug build.  Try running it on the release build.  I should probably break it into two or more smaller tests.

**Comment by spetrunia** [comment]
Confirm, the test succeeds in the release build. It's only debug that fails

**Comment by jkedgar** [comment]
Pull Request: https://github.com/facebook/mysql-5.6/pull/550
