### ISSUE TITLE
MyRocks 2pc calls fdatasync() to WAL, even with reduced durability

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#485]
How to repeat:
rocksdb_disable_2pc=0;
rocksdb_write_sync=0;
sync_binlog=0;

Set gdb breakpoint at fdatasync, then insert any row into MyRocks.
Here is a stacktrace I got:
```
(gdb) bt
#0  0x00007f53a85026d0 in fdatasync () at ../sysdeps/unix/syscall-template.S:81
#1  0x0000000001656560 in rocksdb::PosixWritableFile::Sync() (this=0x7f53a7453780) at /home/yoshinori/local/mysql/5.6/rocksdb/util/io_posix.cc:763
#2  0x0000000001648da5 in rocksdb::WritableFileWriter::SyncInternal(bool) (this=0x7f53a743d3f0, use_fsync=false) at /home/yoshinori/local/mysql/5.6/rocksdb/util/file_reader_writer.cc:242
#3  0x0000000001648ba7 in rocksdb::WritableFileWriter::SyncWithoutFlush(bool) (this=0x7f53a743d3f0, use_fsync=false) at /home/yoshinori/local/mysql/5.6/rocksdb/util/file_reader_writer.cc:230
#4  0x00000000014c21df in rocksdb::DBImpl::SyncWAL() (this=0x7f53a7463000) at /home/yoshinori/local/mysql/5.6/rocksdb/db/db_impl.cc:2703
#5  0x00000000016c4648 in rocksdb::StackableDB::SyncWAL() (this=0x7f53a5daa000) at /home/yoshinori/local/mysql/5.6/rocksdb/include/rocksdb/utilities/stackable_db.h:241
#6  0x0000000001411051 in myrocks::rocksdb_flush_wal(handlerton*, ulonglong) (hton=0x7f53a73bd580, target_lsn=1) at /home/yoshinori/local/mysql/5.6/storage/rocksdb/ha_rocksdb.cc:2615
#7  0x0000000000b9f2ea in flush_handlerton(THD*, plugin_ref, void*) (thd=0x0, plugin=0x7f53aa9b88a8, arg=0x7f53a422e000) at /home/yoshinori/local/mysql/5.6/sql/handler.cc:2441
#8  0x0000000000d94fc5 in plugin_foreach_with_mask(THD*, char (*)(THD*, st_plugin_int**, void*), int, unsigned int, void*) (thd=0x0, func=0xb9f229 <flush_handlerton(THD*, plugin_ref, void*)>, type=1, state_mask=4294967287, arg=0x7f53a422e000) at /home/yoshinori/local/mysql/5.6/sql/sql_plugin.cc:2191
#9  0x0000000000b9f343 in ha_flush_logs(handlerton*, engine_lsn_map*) (db_type=0x0, engine_map=0x7f53a422e000) at /home/yoshinori/local/mysql/5.6/sql/handler.cc:2451
#10 0x0000000001002749 in MYSQL_BIN_LOG::process_flush_stage_queue(unsigned long long*, bool*, THD**, bool) (this=0x25c8780 <mysql_bin_log>, total_bytes_var=0x7f53aa9b89f0, rotate_var=0x7f53aa9b89df, out_queue_var=0x7f53aa9b89f8, async=false) at /home/yoshinori/local/mysql/5.6/sql/binlog.cc:7143
#11 0x00000000010034d4 in MYSQL_BIN_LOG::ordered_commit(THD*, bool, bool, bool) (this=0x25c8780 <mysql_bin_log>, thd=0x7f53a463a000, all=false, skip_commit=false, async=false) at /home/yoshinori/local/mysql/5.6/sql/binlog.cc:7610
#12 0x00000000010023cf in MYSQL_BIN_LOG::commit(THD*, bool, bool) (this=0x25c8780 <mysql_bin_log>, thd=0x7f53a463a000, all=false, async=false) at /home/yoshinori/local/mysql/5.6/sql/binlog.cc:7044
#13 0x0000000000b9d070 in ha_commit_trans(THD*, bool, bool, bool) (thd=0x7f53a463a000, all=false, async=false, ignore_global_read_lock=false) at /home/yoshinori/local/mysql/5.6/sql/handler.cc:1541
#14 0x0000000000e533dd in trans_commit_stmt(THD*, bool) (thd=0x7f53a463a000, async=false) at /home/yoshinori/local/mysql/5.6/sql/transaction.cc:452
#15 0x0000000000d84c89 in mysql_execute_command(THD*, unsigned long long*, unsigned long long*) (thd=0x7f53a463a000, statement_start_time=0x7f53aa9bb4b8, post_parse=0x7f53aa9bb5d0) at /home/yoshinori/local/mysql/5.6/sql/sql_parse.cc:5965
#16 0x0000000000d8841a in mysql_parse(THD*, char*, unsigned int, Parser_state*, unsigned long long*, char*) (thd=0x7f53a463a000, rawbuf=0x7f53a43810b0 "insert into r1 values (7, 1)", length=28, parser_state=0x7f53aa9bbe40, last_timer=0x7f53aa9bb5d0, async_commit=0x7f53aa9bb5a4 "") at /home/yoshinori/local/mysql/5.6/sql/sql_parse.cc:7476
```

Suggested Fix:
rocksdb_flush_wal() needs to check if the instance needs full durability or not. Don't call SyncWAL() if full durability is not required.

**Comment by yoshinorim** [comment]
https://github.com/facebook/mysql-5.6/pull/486
