### ISSUE TITLE
Tests in rocksdb_hotbackup suite fail with 'RESET SLAVE' failed: 1286: Unknown storage engine 'InnoDB'

### ISSUE THREAD

**Issue by spetrunia** [facebook/mysql-5.6#577]
I am using MyRocks, compiled as specified in https://github.com/facebook/mysql-5.6/wiki/Build-Steps.

I'm trying to run tests in rocksdb_hotbackup test suite. They all fail in the same way, like this one:
``` 
~/mysql-5.6/mysql-test$ ./mysql-test-run --suite=rocksdb_hotbackup --force --max-test-fail=100

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 13000..13009
rocksdb_hotbackup.gtid                   [ fail ]
        Test ended at 2017-03-18 09:55:21

CURRENT_TEST: rocksdb_hotbackup.gtid
mysqltest: In included file "./include/rpl_init.inc": 
included from ./include/rpl_init.inc at line 213:
included from ./suite/rocksdb_hotbackup/include/setup.inc at line 4:
At line 213: query 'RESET SLAVE' failed: 1286: Unknown storage engine 'InnoDB'

The result from queries just before the failure was:
include/rpl_init.inc [topology=none]

 - saving '/home/ubuntu/mysql-5.6/mysql-test/var/log/rocksdb_hotbackup.gtid/' to '/home/ubuntu/mysql-5.6/mysql-test/var/log/rocksdb_hotbackup.gtid/'

Retrying test rocksdb_hotbackup.gtid, attempt(2/3)...
```

Every test fails in the same way, so I get:
```
Completed: Failed 6/6 tests, 0.00% were successful.

Failing test(s): rocksdb_hotbackup.gtid rocksdb_hotbackup.slocket rocksdb_hotbackup.stream rocksdb_hotbackup.wdt rocksdb_hotbackup.xbstream rocksdb_hotbackup.xbstream_socket
```

**Comment by spetrunia** [comment]
Checked: my mysqld binary has innodb statically linked in.
An attempt to make dumb fix like this
```diff --git a/mysql-test/suite/rocksdb_hotbackup/base.cnf b/mysql-test/suite/rocksdb_hotbackup/base.cnf
index 101dbce..84af110 100644
--- a/mysql-test/suite/rocksdb_hotbackup/base.cnf
+++ b/mysql-test/suite/rocksdb_hotbackup/base.cnf
@@ -5,7 +5,9 @@
 [mysqld.1]
 rocksdb
 default-storage-engine=rocksdb
-skip-innodb
+#skip-innodb
+allow-multiple-engines
+
 default-tmp-storage-engine=MyISAM
 binlog_format=row
```
didn't make any difference. Tests still fail with the same error.

**Comment by spetrunia** [comment]
All tests fail with the same error

```
At line 213: query 'RESET SLAVE' failed: 1286: Unknown storage engine 'InnoDB'
```

MTR run logs from Centos7 and Ubuntu 16.04:

https://gist.github.com/spetrunia/c4e825bc0a84720dd3a6bac1147be700
https://gist.github.com/spetrunia/62691cf47524c682e2f4eb16b2ba8f26

Running 
```
nm ../sql/mysqld | grep innobase
```

I can see that InnoDB is linked in statically, on both platforms.

**Comment by spetrunia** [comment]
[offtopic] MariaDB's issue for tracking this: https://jira.mariadb.org/browse/MDEV-12380

**Comment by spetrunia** [comment]
Debugged rocksdb_hotbackup.stream test.  The cause of the error is that `RESET SLAVE` statement is trying to clear `mysql.slave_gtid_info`, and fails to open it because the table is using InnoDB storage engine.
I'm not yet sure why is it using InnoDB.

```
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/rpl_info_table_access.cc:148
#1  0x00000000010e8953 in Rpl_info_table::do_reset_info (nparam=3, param_schema=0x19da427 "mysql", 
    param_table=0x19da47b "slave_gtid_info")
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/rpl_info_table.cc:352
#2  0x00000000010d7683 in Rpl_info_factory::reset_gtid_infos (rli=0x2799500)
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/rpl_info_factory.cc:380
#3  0x00000000010b0dd0 in remove_info (mi=0x27f57d0)
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/rpl_slave.cc:1110
#4  0x00000000010c8c62 in reset_slave (thd=0x27fc7f0, mi=0x27f57d0)
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/rpl_slave.cc:9169
#5  0x0000000000e257eb in reload_acl_and_cache (thd=0x27fc7f0, options=64, tables=0x0, 
    write_to_binlog=0x7ffff5699be0) at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/sql_reload.cc:347
#6  0x0000000000dff7b8 in mysql_execute_command (thd=0x27fc7f0, statement_start_time=0x7ffff569a938, 
    post_parse=0x7ffff569aa80) at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/sql_parse.cc:5151
#7  0x0000000000e05af1 in mysql_parse (thd=0x27fc7f0, rawbuf=0x7fffe0005610 "RESET SLAVE", length=11, 
    parser_state=0x7ffff569b310, last_timer=0x7ffff569aa80, async_commit=0x7ffff569aa4c "")
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/sql_parse.cc:7596
#8  0x0000000000df6225 in dispatch_command (command=COM_QUERY, thd=0x27fc7f0, 
    packet=0x280a601 "RESET SLAVE", packet_length=11)
    at /home/psergey/dev-git/mysql-5.6-rocksdb-look400/sql/sql_parse.cc:1719
```

**Comment by spetrunia** [comment]
Ok after installing MySQL-python and when using this command line to start mtr
```
./mysql-test-run --mysqld=--default-storage-engine=rocksdb \
--mysqld=--skip-innodb --mysqld=--default-tmp-storage-engine=\
MyISAM --mysqld=--rocksdb rocksdb_hotbackup.stream
```
the test passed for me on CentOS 7.2.   I suspect there might still be something wrong on Ubuntu, so will keep this bug open for a few more days.

**Comment by spetrunia** [comment]
No, turned out to be a bogus issue after all. Nevermind.
