### ISSUE TITLE
segfault on disconnect from network usage of zstd

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#675]
This occurs on an opensource MyRocks build with Ubuntu 14.10. The build is from June 16 and uses githash 52e058. I also backported this diff to get a working build:
https://github.com/facebook/mysql-5.6/commit/2c2fc539d339a69fa9ef4772f40655262923ec1a

The zstd manual doesn't state whether ZSTD_freeCCtx and ZSTD_freeDCtx can be called with NULL -- http://facebook.github.io/zstd/zstd_manual.html

This diff prevents a segfault when I run "bin/mysqladmin -uroot shutdown" and mysqld isn't running at the time (not sure it matters whether mysqld was running). Ignore the fprintf as that was added to confirm that cctx and dctx were NULL before the segfault.
```
diff --git a/sql/net_serv.cc b/sql/net_serv.cc
index 7593623..9dbe172 100644
--- a/sql/net_serv.cc
+++ b/sql/net_serv.cc
@@ -156,8 +156,9 @@ void net_end(NET *net)
   reset_packet_write_state(net);
 #endif
 #ifdef HAVE_ZSTD_COMPRESS
-  ZSTD_freeCCtx(net->cctx);
-  ZSTD_freeDCtx(net->dctx);
+fprintf(stderr, "net->cctx %p, net->dctx %p\n", net->cctx, net->dctx);
+  if (net->cctx) ZSTD_freeCCtx(net->cctx);
+  if (net->dctx) ZSTD_freeDCtx(net->dctx);
   net->cctx = NULL;
   net->dctx = NULL;
 #endif
```

The stack trace is:
```
(gdb) where
#0  0x00007ffff7ba1664 in ZSTD_freeCCtx () from /usr/lib/x86_64-linux-gnu/libzstd.so.0
#1  0x000000000041e53d in net_end (net=net@entry=0x7fffffffd490) at /home/mdcallag/git/fbmysql.me/sql/net_serv.cc:162
#2  0x000000000041569f in end_server (mysql=mysql@entry=0x7fffffffd490) at /home/mdcallag/git/fbmysql.me/sql-common/client.c:1551
#3  0x000000000041a152 in mysql_real_connect (mysql=mysql@entry=0x7fffffffd490, host=<optimized out>, user=<optimized out>, passwd=<optimized out>,
    db=db@entry=0x0, port=<optimized out>, unix_socket=0x0, client_flag=2147483648) at /home/mdcallag/git/fbmysql.me/sql-common/client.c:4968
#4  0x0000000000408208 in mysql_connect_ssl_check (ssl_required=0 '\000', client_flag=2147483648, unix_socket=<optimized out>, port=<optimized out>, db=0x0,
    passwd=<optimized out>, user=<optimized out>, host=<optimized out>, mysql_arg=0x7fffffffd490) at /home/mdcallag/git/fbmysql.me/client/client_priv.h:186
#5  sql_connect (mysql=mysql@entry=0x7fffffffd490, wait=0) at /home/mdcallag/git/fbmysql.me/client/mysqladmin.cc:554
#6  0x0000000000405f9e in main (argc=1, argv=0x9b3700) at /home/mdcallag/git/fbmysql.me/client/mysqladmin.cc:410
```

zstd is using version 0.5.1-1
```
$ apt show libzstd-dev
Package: libzstd-dev
Version: 0.5.1-1
Priority: optional
Section: universe/libdevel
Source: libzstd
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Med Packaging <debian-med-packaging@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 433 kB
Depends: libzstd0 (= 0.5.1-1)
Homepage: https://github.com/Cyan4973/zstd
Download-Size: 124 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: fast lossless compression algorithm -- development files
 Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting
 real-time compression scenarios at zlib-level compression ratio.
 .
 This package contains the headers and static library.
```

And
```
$ apt show libzstd0
Package: libzstd0
Version: 0.5.1-1
Priority: optional
Section: universe/libs
Source: libzstd
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Med Packaging <debian-med-packaging@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 331 kB
Depends: libc6 (>= 2.14)
Homepage: https://github.com/Cyan4973/zstd
Download-Size: 112 kB
APT-Manual-Installed: no
APT-Sources: http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Description: fast lossless compression algorithm
 Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting
 real-time compression scenarios at zlib-level compression ratio.
 .
 This package contains the shared library.
```

**Comment by mdcallag** [comment]
The problem occurs with 16.04. I am not sure about 14.10. 16.04 is a fairly recent release.

**Comment by jkedgar** [comment]
The ZSTD library was updated to handle this in version 0.7.0, but since 0.5.1-1 is included with Ubuntu I'll update the MyRocks code to handle the older version.

**Comment by jkedgar** [comment]
Fixed and closed.  https://github.com/facebook/mysql-5.6/commit/bfc45c8b40952466db396b210d28a4e5e02a03ad
