### ISSUE TITLE
crash when playing with rocksdb_update_cf_options variable

### ISSUE THREAD

**Issue by tplavcic** [facebook/mysql-5.6#696]
Noticed a crash when playing with rocksdb_update_cf_options dynamic option.

Options for starting:
`--no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB`

TEST CASE:
```
create table t1(a int, primary key(a) comment 'cf1') engine=rocksdb;
SET @@global.rocksdb_update_cf_options = 'cf1={write_buffer_size=8m;target_file_size_base=2m};';
SET @@global.rocksdb_update_cf_options = NULL;
SET @@global.rocksdb_update_cf_options = NULL;
SET @@global.rocksdb_update_cf_options = NULL;
SET @@global.rocksdb_update_cf_options = 'cf1={write_buffer_size=8m;target_file_size_base=2m};';
drop table t1;
SET @@global.rocksdb_update_cf_options = 'cf1={write_buffer_size=8m;target_file_size_base=2m};';
```

GDB INFO:
```
Core was generated by `/ssd/tomislav/mysql-5.6.35-linux-x86_64/bin/mysqld --no-defaults --default-tmp-'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __pthread_kill (threadid=<optimized out>, signo=signo@entry=11) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
62      ../sysdeps/unix/sysv/linux/pthread_kill.c: No such file or directory.
[Current thread is 1 (Thread 0x7f401f9b0700 (LWP 2434))]
(gdb) bt
#0  __pthread_kill (threadid=<optimized out>, signo=signo@entry=11) at ../sysdeps/unix/sysv/linux/pthread_kill.c:62
#1  0x0000000000b2ea17 in my_write_core (sig=sig@entry=11) at /ssd/tomislav/mysql-5.6/mysys/stacktrace.c:424
#2  0x000000000084327e in handle_fatal_signal (sig=11) at /ssd/tomislav/mysql-5.6/sql/signal_handler.cc:239
#3  <signal handler called>
#4  0x0000000000000000 in ?? ()
#5  0x0000000000ecef3b in rocksdb::(anonymous namespace)::ReadOneLine (result=0x7f401f9aa930, has_data=<synthetic pointer>, output=0x7f401f9aaa20, seq_file=0x7f4011c190c0, iss=0x7f401f9aaae0)
    at /ssd/tomislav/mysql-5.6/rocksdb/options/options_parser.cc:218
#6  rocksdb::RocksDBOptionsParser::Parse (this=this@entry=0x7f401f9abd40, file_name="./.rocksdb/OPTIONS-000028.dbtmp", env=env@entry=0x19384a0 <rocksdb::Env::Default()::default_env>,
    ignore_unknown_options=ignore_unknown_options@entry=false) at /ssd/tomislav/mysql-5.6/rocksdb/options/options_parser.cc:256
#7  0x0000000000ecf7b8 in rocksdb::RocksDBOptionsParser::VerifyRocksDBOptionsFromFile (db_opt=..., cf_names=std::vector of length 3, capacity 4 = {...},
    cf_opts=std::vector of length 3, capacity 4 = {...}, file_name="./.rocksdb/OPTIONS-000028.dbtmp", env=env@entry=0x19384a0 <rocksdb::Env::Default()::default_env>,
    sanity_check_level=rocksdb::kSanityLevelExactMatch, ignore_unknown_options=false) at /ssd/tomislav/mysql-5.6/rocksdb/options/options_parser.cc:626
#8  0x0000000000ed104d in rocksdb::PersistRocksDBOptions (db_opt=..., cf_names=std::vector of length 3, capacity 4 = {...}, cf_opts=std::vector of length 3, capacity 4 = {...},
    file_name="./.rocksdb/OPTIONS-000028.dbtmp", env=0x19384a0 <rocksdb::Env::Default()::default_env>) at /ssd/tomislav/mysql-5.6/rocksdb/options/options_parser.cc:101
#9  0x0000000000dc4ceb in rocksdb::DBImpl::WriteOptionsFile (this=this@entry=0x7f401ce57c00, need_mutex_lock=need_mutex_lock@entry=false, need_enter_write_thread=need_enter_write_thread@entry=true)
    at /ssd/tomislav/mysql-5.6/rocksdb/db/db_impl.cc:2373
#10 0x0000000000dc6446 in rocksdb::DBImpl::SetOptions (this=0x7f401ce57c00, column_family=<optimized out>, options_map=std::unordered_map with 2 elements = {...})
    at /ssd/tomislav/mysql-5.6/rocksdb/db/db_impl.cc:501
#11 0x0000000000d6c122 in rocksdb::StackableDB::SetOptions (new_options=std::unordered_map with 2 elements = {...}, column_family_handle=0x7f4011c11160, this=<optimized out>)
    at /ssd/tomislav/mysql-5.6/rocksdb/include/rocksdb/utilities/stackable_db.h:323
#12 myrocks::rocksdb_set_update_cf_options (var_ptr=0x1928cd0 <myrocks::rocksdb_update_cf_options>, save=<optimized out>) at /ssd/tomislav/mysql-5.6/storage/rocksdb/ha_rocksdb.cc:11786
#13 0x00000000008e378f in plugin_var_memalloc_global_update (value=0x7f4011c433a0 "cf1={write_buffer_size=8m;target_file_size_base=2m};", dest=<optimized out>, var=<optimized out>, thd=0x7f4019ee0000)
    at /ssd/tomislav/mysql-5.6/sql/sql_plugin.cc:3126
#14 sys_var_pluginvar::global_update (this=<optimized out>, thd=0x7f4019ee0000, var=<optimized out>) at /ssd/tomislav/mysql-5.6/sql/sql_plugin.cc:3310
#15 0x0000000000841cf6 in sys_var::update (var=0x7f4011c43300, thd=0x7f4019ee0000, this=0x7f401cf8ef80) at /ssd/tomislav/mysql-5.6/sql/set_var.cc:193
#16 set_var::update (this=0x7f4011c43300, thd=0x7f4019ee0000) at /ssd/tomislav/mysql-5.6/sql/set_var.cc:763
#17 0x00000000008429f9 in <lambda(THD*, set_var_base*)>::operator() (__closure=<optimized out>, var=<optimized out>, each_thd=<optimized out>) at /ssd/tomislav/mysql-5.6/sql/set_var.cc:667
#18 <lambda(THD*, set_var_base*)>::_FUN () at /ssd/tomislav/mysql-5.6/sql/set_var.cc:668
#19 process_set_variable_map (func=<optimized out>, map=std::unordered_map with 1 element = {...}, current_thd_id=1, thd=0x7f4019ee0000) at /ssd/tomislav/mysql-5.6/sql/set_var.cc:593
#20 sql_set_variables (thd=thd@entry=0x7f4019ee0000, var_list=var_list@entry=0x7f4019ee40a8) at /ssd/tomislav/mysql-5.6/sql/set_var.cc:668
#21 0x00000000008d7009 in mysql_execute_command (thd=thd@entry=0x7f4019ee0000, statement_start_time=statement_start_time@entry=0x7f401f9ae758, post_parse=post_parse@entry=0x7f401f9ae8a8)
    at /ssd/tomislav/mysql-5.6/sql/sql_parse.cc:4805
#22 0x00000000008db1a8 in mysql_parse (thd=thd@entry=0x7f4019ee0000, rawbuf=<optimized out>, length=<optimized out>, parser_state=parser_state@entry=0x7f401f9af180,
    last_timer=last_timer@entry=0x7f401f9ae8a8, async_commit=async_commit@entry=0x7f401f9ae8a7 "") at /ssd/tomislav/mysql-5.6/sql/sql_parse.cc:7783
#23 0x00000000008dc377 in dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=0x7f4019ee0000,
    packet=packet@entry=0x7f4019f4a001 "SET @@global.rocksdb_update_cf_options = 'cf1={write_buffer_size=8m;target_file_size_base=2m};'", packet_length=packet_length@entry=95,
    srv_session=srv_session@entry=0x0) at /ssd/tomislav/mysql-5.6/sql/sql_parse.cc:1862
#24 0x00000000008dec18 in do_command (thd=0x7f4019ee0000) at /ssd/tomislav/mysql-5.6/sql/sql_parse.cc:1207
#25 0x000000000089b28c in do_handle_one_connection (thd_arg=<optimized out>) at /ssd/tomislav/mysql-5.6/sql/sql_connect.cc:1142
#26 0x000000000089b519 in handle_one_connection (arg=<optimized out>) at /ssd/tomislav/mysql-5.6/sql/sql_connect.cc:963
#27 0x00007f401e2ac6ba in start_thread (arg=0x7f401f9b0700) at pthread_create.c:333
#28 0x00007f401d73a3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

Reported here: https://jira.percona.com/browse/MYR-175 also with some more examples and MTR test created by George.
In my case here jemmalloc was LD_PRELOADED, as you may see in MYR-175 without using jemalloc it's a little bit different.

**Comment by hermanlee** [comment]
Thanks for filing the issue with a test case. I can reproduce this and we will investigate the problem.
