### ISSUE TITLE
segfault with 3.23.2 build of HHVM

### ISSUE THREAD

**Issue by anoakie** [facebook/mysql-5.6#766]
I'm getting this segfault with the latest build of HHVM.  I saw this issue here: https://github.com/facebook/hhvm/issues/8050, which I'm guessing is related to what I'm seeing, but I don't see the followup issue here. 

```HipHop VM 3.23.2 (rel)
Compiler: 1511206599_661801426
Repo schema: 57a6d72ee7a93fe666bcfd7e75d7e2e160e38911
```

Here is some gdb info.  I've XXX'd out sensitive stuff.

```Thread 3 "hhvm" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f5b12fff700 (LWP 553195)]
net_field_length (packet=packet@entry=0x7f5b12ff6d00) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/pack.c:25
25      /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/pack.c: No such file or directory.
(gdb) bt
#0  net_field_length (packet=packet@entry=0x7f5b12ff6d00) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/pack.c:25
#1  0x0000000001f9957c in read_ok_ex (mysql=mysql@entry=0x7f5b1fd2f200, length=length@entry=107) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/client.c:723
#2  0x00000000023a09e3 in cli_read_query_result (mysql=0x7f5b1fd2f200) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/client.c:6328
#3  0x0000000001f934e5 in execute (stmt=0x7f5b17ec7080, packet=packet@entry=0x0, length=length@entry=0) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/libmysql/libmysql.c:2109
#4  0x0000000001f95639 in cli_stmt_execute (stmt=0x7f5b17ec7080) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/libmysql/libmysql.c:2246
#5  0x0000000001f970ca in mysql_stmt_execute (stmt=0x7f5b17ec7080) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/libmysql/libmysql.c:2632
#6  0x0000000001d557bc in HPHP::PDOMySqlStatement::executePrepared (this=0x7f5b17c2da20) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/hphp/runtime/ext/pdo_mysql/pdo_mysql.cpp:679
#7  0x0000000001b6c7ae in HPHP::c_PDOStatement_ni_execute (this_=0x7f5b17ca34c0, paramsV=...) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/hphp/runtime/ext/pdo/ext_pdo.cpp:2707
#8  0x00000000013166ef in HPHP::Native::callFuncIndirectImpl<HPHP::Variant> (f=<optimized out>, GP=GP@entry=0x7f5b12ff70a0, GP_count=<optimized out>, SIMD=SIMD@entry=0x7f5b12ff7060,
    SIMD_count=SIMD_count@entry=0) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/hphp/runtime/vm/native-func-caller.h:2253
#9  0x000000000131c120 in HPHP::Native::callFunc<false> (func=func@entry=0x7f5b188df980, ctx=<optimized out>, args=args@entry=0x7f5b18f7edf0, numNonDefault=numNonDefault@entry=0, ret=...)
    at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/hphp/runtime/vm/native.cpp:202
...

(gdb) print packet
$1 = (uchar **) 0x7f5b12ff6d00
(gdb) print *packet
$2 = (uchar *) 0x7f5b12800000 ""
(gdb) print pos
$3 = (uchar *) 0x7f5b12800000 ""
(gdb) print *pos
$4 = 0 '\000'
(gdb) up 3
#3  0x0000000001f934e5 in execute (stmt=0x7f5b17ec7080, packet=packet@entry=0x0, length=length@entry=0) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/libmysql/libmysql.c:2109
2109    /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/libmysql/libmysql.c: No such file or directory.
(gdb) print *stmt
$5 = {mem_root = {free = 0x7f5b18efb200, used = 0x0, pre_alloc = 0x7f5b18efb200, min_malloc = 32, block_size = 2016, block_num = 4, first_block_usage = 0, max_capacity = 0, allocated_size = 2064, 
    error_for_capacity_exceeded = 0 '\000', error_handler = 0x0}, list = {prev = 0x0, next = 0x0, data = 0x7f5b17ec7080}, mysql = 0x7f5b1fd2f200, params = 0x7f5b18efb210, bind = 0x7f5b18efb210, fields = 0x0, 
  result = {data = 0x0, embedded_info = 0x0, alloc = {free = 0x7f5b17e1f000, used = 0x0, pre_alloc = 0x7f5b17e1f000, min_malloc = 24, block_size = 4064, block_num = 4, first_block_usage = 0, 
      max_capacity = 0, allocated_size = 4112, error_for_capacity_exceeded = 0 '\000', error_handler = 0x0}, rows = 0, fields = 0, extension = 0x0}, data_cursor = 0x0, 
  read_row_func = 0x1f912f0 <stmt_read_row_no_result_set>, affected_rows = 0, insert_id = 0, stmt_id = 1, flags = 0, prefetch_rows = 1, server_status = 0, last_errno = 0, param_count = 0, field_count = 0, 
  state = MYSQL_STMT_PREPARE_DONE, last_error = '\000' <repeats 511 times>, sqlstate = "00000", send_types_to_server = 0 '\000', bind_param_done = 0 '\000', bind_result_done = 0 '\000', 
  unbuffered_fetch_cancelled = 0 '\000', update_max_length = 0 '\000', extension = 0x7f5b18f3f7e0}
...
(gdb) down
#2  0x00000000023a09e3 in cli_read_query_result (mysql=0x7f5b1fd2f200) at /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/client.c:6328
6328    /tmp/hhvmpkg.utS0sdfy/hhvm-3.23.2/third-party/webscalesqlclient/src/sql-common/client.c: No such file or directory.
(gdb) print *mysql
$19 = {net = {vio = 0x7f5b17e17280, buff = 0x7f5b0e629000 "", buff_end = 0x7f5b0e62b000 "", write_pos = 0x7f5b0e629000 "", read_pos = 0x7f5b0e629000 "", fd = 26, remain_in_buf = 0, length = 0, 
    buf_length = 0, where_b = 0, max_packet = 8192, max_packet_size = 1073741824, pkt_nr = 2, compress_pkt_nr = 2, write_timeout = {value_ms_ = 4294967295}, read_timeout = {value_ms_ = 4294967295}, 
    retry_count = 1, fcntl = 0, return_status = 0x0, reading_or_writing = 0 '\000', save_char = 0 '\000', unused1 = 0 '\000', unused2 = 0 '\000', compress = 0 '\000', compress_event = 0 '\000', 
    unused3 = 0 '\000', comp_lib = MYSQL_COMPRESSION_ZLIB, cctx = 0x0, dctx = 0x0, unused = 0x0, last_errno = 0, error = 0 '\000', unused4 = 0 '\000', unused5 = 0 '\000', 
    last_error = '\000' <repeats 511 times>, sqlstate = "00000", extension = 0x0, cur_pos = 0x0, ssl = 0x0, async_blocking_state = 0, async_operation = NET_ASYNC_OP_IDLE, async_bytes_wanted = 0, 
    read_rows_is_first_read = 1 '\001', async_send_command_status = NET_ASYNC_SEND_COMMAND_IDLE, async_read_query_result_status = NET_ASYNC_READ_QUERY_RESULT_IDLE, 
    async_packet_read_state = NET_ASYNC_PACKET_READ_IDLE, async_packet_length = 0, async_packet_uncompressed_length = 0, multi_packet_offset = 0, async_write_headers = 0x0, async_write_vector = 0x0, 
    async_write_vector_size = 0, async_write_vector_current = 0, inline_async_write_header = '\000' <repeats 12 times>, inline_async_write_vector = {{iov_base = 0x0, iov_len = 0}, {iov_base = 0x0, 
        iov_len = 0}, {iov_base = 0x0, iov_len = 0}}, compressed_write_buffers = 0x0, compressed_buffers_size = 0, async_multipacket_read_saved_whereb = 0, async_multipacket_read_total_len = 0, 
    async_multipacket_read_started = 0 '\000', receive_buffer_size = 0}, connector_fd = 0x0, host = XX "XXX", user = XXX "XXX", 
  passwd = XXX "XXX", unix_socket = 0x0, server_version = XXX "XXX", host_info = XXX "XXX", info = 0x0, 
  db = XXX "XXX", charset = 0x34bee60 <my_charset_latin1>, fields = 0x0, field_alloc = {free = 0x0, used = 0x0, pre_alloc = 0x0, min_malloc = 32, block_size = 8160, block_num = 4, 
    first_block_usage = 0, max_capacity = 0, allocated_size = 0, error_for_capacity_exceeded = 0 '\000', error_handler = 0x0}, affected_rows = 0, insert_id = 0, extra_info = 0, thread_id = 220693798, 
  packet_length = 0, port = 3306, client_flag = 12558861, server_capabilities = 3254779903, protocol_version = 10, field_count = 0, server_status = 16386, server_language = 8, warning_count = 0, options = {
    connect_timeout = {value_ms_ = 30000}, read_timeout = {value_ms_ = 4294967295}, write_timeout = {value_ms_ = 4294967295}, port = 0, protocol = 0, client_flag = 0, host = 0x0, user = 0x0, password = 0x0, 
    unix_socket = 0x0, db = 0x0, init_commands = 0x0, my_cnf_file = 0x0, my_cnf_group = 0x0, charset_dir = 0x0, charset_name = 0x7f5b18e0da98 "latin1", ssl_key = 0x0, ssl_cert = 0x0, ssl_ca = 0x0, 
    ssl_capath = 0x0, ssl_cipher = 0x0, shared_memory_base_name = 0x0, max_allowed_packet = 0, use_ssl = 0 '\000', compress = 0 '\000', compress_event = 0 '\000', named_pipe = 0 '\000', unused1 = 0 '\000', 
    unused2 = 0 '\000', unused3 = 0 '\000', unused4 = 0 '\000', methods_to_use = MYSQL_OPT_GUESS_CONNECTION, ci = {client_ip = 0x0, bind_address = 0x0}, secure_auth = 1 '\001', 
    report_data_truncation = 1 '\001', local_infile_init = 0x0, local_infile_read = 0x0, local_infile_end = 0x0, local_infile_error = 0x0, local_infile_userdata = 0x0, extension = 0x7f5b0e63dbc0}, 
  status = MYSQL_STATUS_READY, free_me = 1 '\001', reconnect = 0 '\000', scramble = "XXX", unused1 = 0 '\000', unused2 = 0x0, unused3 = 0x0, unused4 = 0x0, unused5 = 0x0, 
  stmts = 0x7f5b17ec70d0, methods = 0x34be180 <client_methods>, thd = 0x0, unbuffered_fetch_owner = 0x0, info_buffer = 0x0, extension = 0x7f5b18e95ac0, rows_result_buffer = 0x0, prev_row_ptr = 0x0, 
  connect_context = 0x0, async_op_status = ASYNC_OP_UNSET, async_query_length = 0, async_query_state = QUERY_IDLE, recv_gtid = 0x0}

```

**Comment by jsonfry** [comment]
We're seeing a segfault on mysql connection too. I've noticed it's fine if the database name is at least 5 characters long.
