### ISSUE TITLE
segfault using bogus rocksdb_tmpdir and custom/new column family

### ISSUE THREAD

**Issue by george-lorch** [facebook/mysql-5.6#901]
Reproduced on commit 04491dbffb51146ab63eea76ba2eb1dab840115f

Consider this test case:
> CREATE DATABASE test;
> USE test;
> set session rocksdb_tmpdir='a';
> CREATE TABLE t1(c1 YEAR,c2 BINARY,c3 INT,c4 BINARY KEY,c5 YEAR UNIQUE KEY,c6 DECIMAL(0,0)DEFAULT 3.141592) ENGINE=ROCKSDB;
> CREATE INDEX i1_3 ON t1(c1,c2,c3) COMMENT '0';
> DROP TABLE t1;

Will segfault with this backtrace:
> Thread 7 "myrocks-index" received signal SIGABRT, Aborted.
> [Switching to Thread 0x7fffe97fa700 (LWP 10381)]
> __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
> 51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> (gdb) bt
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
> #1  0x00007ffff5915801 in __GI_abort () at abort.c:79
> #2  0x0000555556bca5b9 in myrocks::Rdb_drop_index_thread::run (this=0x555557f3bc80 <myrocks::rdb_drop_idx_thread>) at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/ha_rocksdb.cc:10835
> #3  0x0000555556c97202 in myrocks::Rdb_thread::thread_func (thread_ptr=0x555557f3bc80 <myrocks::rdb_drop_idx_thread>) at /home/glorch/dev/ps/facebook-mysql/storage/rocksdb/rdb_threads.cc:32
> #4  0x0000555556ba051c in pfs_spawn_thread (arg=0x555558378b70) at /home/glorch/dev/ps/facebook-mysql/storage/perfschema/pfs.cc:1860
> #5  0x00007ffff660c6db in start_thread (arg=0x7fffe97fa700) at pthread_create.c:463
> #6  0x00007ffff59f688f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

I have not diagnosed this much but I believe this is a negative interaction between a 'bad' rocksdb_tmpdir and a new/custom column family.

**Comment by RoelVdP** [comment]
Also, this error can be seen on PS 8.0.13;

```
8.0.13>CREATE INDEX i1_3 ON t1(c1,c2,c3) COMMENT '0';
ERROR 1 (HY000): Can't create/write to file 'a/myrocks9PN093' (OS errno 2 - No such file or directory)
```
